package com.github.megatronking.svg.sample.drawables;

import android.content.Context;
import android.graphics.Canvas;
import android.graphics.ColorFilter;
import android.graphics.Paint;

import com.github.megatronking.svg.support.SVGRenderer;

/**
 * AUTO-GENERATED FILE.  DO NOT MODIFY.
 * 
 * This class was automatically generated by the
 * SVG-Generator. It should not be modified by hand.
 */
public class ic_look_more extends SVGRenderer {

    public ic_look_more(Context context) {
        super(context);
        mAlpha = 1.0f;
        mWidth = dip2px(48.0f);
        mHeight = dip2px(48.0f);
    }

    @Override
    public void render(Canvas canvas, int w, int h, ColorFilter filter) {
        final float scaleX = w / 100.0f;
        final float scaleY = h / 100.0f;
        
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(50.0f, 50.0f);
        mPath.rMoveTo(-40.0f, 0.0f);
        mPath.cubicTo(10.0f, 39.39541f, 14.217151f, 29.214308f, 21.715729f, 21.715729f);
        mPath.cubicTo(29.214308f, 14.217151f, 39.39541f, 10.0f, 50.0f, 10.0f);
        mPath.cubicTo(60.60459f, 10.0f, 70.78569f, 14.217151f, 78.28427f, 21.715729f);
        mPath.cubicTo(85.78285f, 29.214308f, 90.0f, 39.39541f, 90.0f, 50.0f);
        mPath.cubicTo(90.0f, 60.60459f, 85.78285f, 70.78569f, 78.28427f, 78.28427f);
        mPath.cubicTo(70.78569f, 85.78285f, 60.60459f, 90.0f, 50.0f, 90.0f);
        mPath.cubicTo(39.39541f, 90.0f, 29.214308f, 85.78285f, 21.715729f, 78.28427f);
        mPath.cubicTo(14.217151f, 70.78569f, 10.0f, 60.60459f, 10.0f, 50.0f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        if (mFillPaint == null) {
            mFillPaint = new Paint();
            mFillPaint.setStyle(Paint.Style.FILL);
            mFillPaint.setAntiAlias(true);
        }
        mFillPaint.setColor(applyAlpha(-16777216, 1.0f));
        mFillPaint.setColorFilter(filter);
        canvas.drawPath(mRenderPath, mFillPaint);

    }

}