package com.github.megatronking.svg.iconlibs;

import android.content.Context;
import android.graphics.Canvas;
import android.graphics.ColorFilter;
import android.graphics.Paint;

import com.github.megatronking.svg.support.SVGRenderer;

/**
 * AUTO-GENERATED FILE.  DO NOT MODIFY.
 * 
 * This class was automatically generated by the
 * SVG-Generator. It should not be modified by hand.
 */
public class ic_airline_seat_recline_normal extends SVGRenderer {

    public ic_airline_seat_recline_normal(Context context) {
        super(context);
        mAlpha = 1.0f;
        mWidth = dip2px(24.0f);
        mHeight = dip2px(24.0f);
    }

    @Override
    public void render(Canvas canvas, int w, int h, ColorFilter filter) {
        final float scaleX = w / 24.0f;
        final float scaleY = h / 24.0f;
        
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(7.59f, 5.41f);
        mPath.rCubicTo(-0.78f, -0.78f, -0.78f, -2.05f, 0.0f, -2.83f);
        mPath.rCubicTo(0.78f, -0.78f, 2.05f, -0.78f, 2.83f, 0.0f);
        mPath.rCubicTo(0.78f, 0.78f, 0.78f, 2.05f, 0.0f, 2.83f);
        mPath.rCubicTo(-0.79f, 0.79f, -2.05f, 0.79f, -2.83f, 0.0f);
        mPath.close();
        mPath.moveTo(7.59f, 5.41f);
        mPath.moveTo(6.0f, 16.0f);
        mPath.lineTo(6.0f, 7.0f);
        mPath.lineTo(4.0f, 7.0f);
        mPath.rLineTo(0f, 9.0f);
        mPath.rCubicTo(0.0f, 2.76f, 2.24f, 5.0f, 5.0f, 5.0f);
        mPath.rLineTo(6.0f, 0f);
        mPath.rLineTo(0f, -2.0f);
        mPath.lineTo(9.0f, 19.0f);
        mPath.rCubicTo(-1.66f, 0.0f, -3.0f, -1.34f, -3.0f, -3.0f);
        mPath.close();
        mPath.moveTo(6.0f, 16.0f);
        mPath.rMoveTo(14.0f, 4.07f);
        mPath.lineTo(14.93f, 15.0f);
        mPath.lineTo(11.5f, 15.0f);
        mPath.rLineTo(0f, -3.68f);
        mPath.rCubicTo(1.4f, 1.15f, 3.6f, 2.16f, 5.5f, 2.16f);
        mPath.rLineTo(0f, -2.16f);
        mPath.rCubicTo(-1.66f, 0.02f, -3.61f, -0.87f, -4.67f, -2.04f);
        mPath.rLineTo(-1.4f, -1.55f);
        mPath.rCubicTo(-0.19f, -0.21f, -0.43f, -0.38f, -0.69f, -0.5f);
        mPath.rCubicTo(-0.29f, -0.14f, -0.62f, -0.23f, -0.96f, -0.23f);
        mPath.rLineTo(-0.03f, 0f);
        mPath.cubicTo(8.01f, 7.0f, 7.0f, 8.01f, 7.0f, 9.25f);
        mPath.lineTo(7.0f, 15.0f);
        mPath.rCubicTo(0.0f, 1.66f, 1.34f, 3.0f, 3.0f, 3.0f);
        mPath.rLineTo(5.07f, 0f);
        mPath.rLineTo(3.5f, 3.5f);
        mPath.lineTo(20.0f, 20.07f);
        mPath.close();
        mPath.moveTo(20.0f, 20.07f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        if (mFillPaint == null) {
            mFillPaint = new Paint();
            mFillPaint.setStyle(Paint.Style.FILL);
            mFillPaint.setAntiAlias(true);
        }
        mFillPaint.setColor(applyAlpha(-16777216, 1.0f));
        mFillPaint.setColorFilter(filter);
        canvas.drawPath(mRenderPath, mFillPaint);

    }

}