package com.github.megatronking.svg.iconlibs;

import android.content.Context;
import android.graphics.Canvas;
import android.graphics.ColorFilter;
import android.graphics.Paint;

import com.github.megatronking.svg.support.SVGRenderer;

/**
 * AUTO-GENERATED FILE.  DO NOT MODIFY.
 * 
 * This class was automatically generated by the
 * SVG-Generator. It should not be modified by hand.
 */
public class ic_airline_seat_flat extends SVGRenderer {

    public ic_airline_seat_flat(Context context) {
        super(context);
        mAlpha = 1.0f;
        mWidth = dip2px(24.0f);
        mHeight = dip2px(24.0f);
    }

    @Override
    public void render(Canvas canvas, int w, int h, ColorFilter filter) {
        final float scaleX = w / 24.0f;
        final float scaleY = h / 24.0f;
        
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(22.0f, 11.0f);
        mPath.rLineTo(0f, 2.0f);
        mPath.lineTo(9.0f, 13.0f);
        mPath.lineTo(9.0f, 7.0f);
        mPath.rLineTo(9.0f, 0f);
        mPath.rCubicTo(2.21f, 0.0f, 4.0f, 1.79f, 4.0f, 4.0f);
        mPath.close();
        mPath.moveTo(22.0f, 11.0f);
        mPath.moveTo(2.0f, 14.0f);
        mPath.rLineTo(0f, 2.0f);
        mPath.rLineTo(6.0f, 0f);
        mPath.rLineTo(0f, 2.0f);
        mPath.rLineTo(8.0f, 0f);
        mPath.rLineTo(0f, -2.0f);
        mPath.rLineTo(6.0f, 0f);
        mPath.rLineTo(0f, -2.0f);
        mPath.lineTo(2.0f, 14.0f);
        mPath.close();
        mPath.moveTo(2.0f, 14.0f);
        mPath.rMoveTo(5.14f, -1.9f);
        mPath.rCubicTo(1.16f, -1.19f, 1.14f, -3.08f, -0.04f, -4.24f);
        mPath.rCubicTo(-1.19f, -1.16f, -3.08f, -1.14f, -4.24f, 0.04f);
        mPath.rCubicTo(-1.16f, 1.19f, -1.14f, 3.08f, 0.04f, 4.24f);
        mPath.rCubicTo(1.19f, 1.16f, 3.08f, 1.14f, 4.24f, -0.04f);
        mPath.close();
        mPath.moveTo(7.14f, 12.1f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        if (mFillPaint == null) {
            mFillPaint = new Paint();
            mFillPaint.setStyle(Paint.Style.FILL);
            mFillPaint.setAntiAlias(true);
        }
        mFillPaint.setColor(applyAlpha(-16777216, 1.0f));
        mFillPaint.setColorFilter(filter);
        canvas.drawPath(mRenderPath, mFillPaint);

    }

}