package com.github.megatronking.svg.iconlibs;

import android.content.Context;
import android.graphics.Canvas;
import android.graphics.ColorFilter;
import android.graphics.Paint;

import com.github.megatronking.svg.support.SVGRenderer;

/**
 * AUTO-GENERATED FILE.  DO NOT MODIFY.
 * 
 * This class was automatically generated by the
 * SVG-Generator. It should not be modified by hand.
 */
public class ic_phone_missed extends SVGRenderer {

    public ic_phone_missed(Context context) {
        super(context);
        mAlpha = 1.0f;
        mWidth = dip2px(24.0f);
        mHeight = dip2px(24.0f);
    }

    @Override
    public void render(Canvas canvas, int w, int h, ColorFilter filter) {
        final float scaleX = w / 24.0f;
        final float scaleY = h / 24.0f;
        
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(6.5f, 5.5f);
        mPath.lineTo(12.0f, 11.0f);
        mPath.rLineTo(7.0f, -7.0f);
        mPath.rLineTo(-1.0f, -1.0f);
        mPath.rLineTo(-6.0f, 6.0f);
        mPath.rLineTo(-4.5f, -4.5f);
        mPath.lineTo(11.0f, 4.5f);
        mPath.lineTo(11.0f, 3.0f);
        mPath.lineTo(5.0f, 3.0f);
        mPath.rLineTo(0f, 6.0f);
        mPath.rLineTo(1.5f, 0f);
        mPath.lineTo(6.5f, 5.5f);
        mPath.close();
        mPath.moveTo(6.5f, 5.5f);
        mPath.rMoveTo(17.21f, 11.17f);
        mPath.cubicTo(20.66f, 13.78f, 16.54f, 12.0f, 12.0f, 12.0f);
        mPath.cubicTo(7.46f, 12.0f, 3.34f, 13.78f, 0.29f, 16.67f);
        mPath.rCubicTo(-0.18f, 0.18f, -0.29f, 0.43f, -0.29f, 0.71f);
        mPath.rCubicTo(0.0f, 0.27999878f, 0.11f, 0.53f, 0.29f, 0.71f);
        mPath.rLineTo(2.48f, 2.48f);
        mPath.rCubicTo(0.18f, 0.18f, 0.43f, 0.29f, 0.71f, 0.29f);
        mPath.rCubicTo(0.27f, 0.0f, 0.52f, -0.11f, 0.7f, -0.28f);
        mPath.rCubicTo(0.79f, -0.74f, 1.69f, -1.36f, 2.66f, -1.85f);
        mPath.rCubicTo(0.33f, -0.16f, 0.56f, -0.5f, 0.56f, -0.9f);
        mPath.rLineTo(0f, -3.1f);
        mPath.rCubicTo(1.45f, -0.48f, 3.0f, -0.73f, 4.6f, -0.73f);
        mPath.rCubicTo(1.6f, 0.0f, 3.15f, 0.25f, 4.6f, 0.72f);
        mPath.rLineTo(0f, 3.1f);
        mPath.rCubicTo(0.0f, 0.39f, 0.23f, 0.74f, 0.56f, 0.9f);
        mPath.rCubicTo(0.98f, 0.49f, 1.87f, 1.12f, 2.67f, 1.85f);
        mPath.rCubicTo(0.18f, 0.18f, 0.43f, 0.28f, 0.7f, 0.28f);
        mPath.rCubicTo(0.28f, 0.0f, 0.53f, -0.11f, 0.71f, -0.29f);
        mPath.rLineTo(2.48f, -2.48f);
        mPath.rCubicTo(0.18f, -0.18f, 0.29f, -0.43f, 0.29f, -0.71f);
        mPath.rCubicTo(0.0f, -0.27999878f, -0.12f, -0.52f, -0.3f, -0.7f);
        mPath.close();
        mPath.moveTo(23.71f, 16.67f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        if (mFillPaint == null) {
            mFillPaint = new Paint();
            mFillPaint.setStyle(Paint.Style.FILL);
            mFillPaint.setAntiAlias(true);
        }
        mFillPaint.setColor(applyAlpha(-16777216, 1.0f));
        mFillPaint.setColorFilter(filter);
        canvas.drawPath(mRenderPath, mFillPaint);

    }

}