package com.github.megatronking.svg.iconlibs;

import android.content.Context;
import android.graphics.Canvas;
import android.graphics.ColorFilter;
import android.graphics.Paint;

import com.github.megatronking.svg.support.SVGRenderer;

/**
 * AUTO-GENERATED FILE.  DO NOT MODIFY.
 * 
 * This class was automatically generated by the
 * SVG-Generator. It should not be modified by hand.
 */
public class ic_sync_disabled extends SVGRenderer {

    public ic_sync_disabled(Context context) {
        super(context);
        mAlpha = 1.0f;
        mWidth = dip2px(24.0f);
        mHeight = dip2px(24.0f);
    }

    @Override
    public void render(Canvas canvas, int w, int h, ColorFilter filter) {
        final float scaleX = w / 24.0f;
        final float scaleY = h / 24.0f;
        
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(10.0f, 6.35f);
        mPath.lineTo(10.0f, 4.26f);
        mPath.rCubicTo(-0.8f, 0.21f, -1.55f, 0.54f, -2.23f, 0.96f);
        mPath.rLineTo(1.46f, 1.46f);
        mPath.rCubicTo(0.25f, -0.12f, 0.5f, -0.24f, 0.77f, -0.33f);
        mPath.close();
        mPath.moveTo(10.0f, 6.35f);
        mPath.rMoveTo(-7.14f, -0.94f);
        mPath.rLineTo(2.36f, 2.36f);
        mPath.cubicTo(4.45f, 8.99f, 4.0f, 10.44f, 4.0f, 12.0f);
        mPath.rCubicTo(0.0f, 2.21f, 0.91f, 4.2f, 2.36f, 5.64f);
        mPath.lineTo(4.0f, 20.0f);
        mPath.rLineTo(6.0f, 0f);
        mPath.rLineTo(0f, -6.0f);
        mPath.rLineTo(-2.24f, 2.24f);
        mPath.cubicTo(6.68f, 15.15f, 6.0f, 13.66f, 6.0f, 12.0f);
        mPath.rCubicTo(0.0f, -1.0f, 0.25f, -1.94f, 0.68f, -2.77f);
        mPath.rLineTo(8.08f, 8.08f);
        mPath.rCubicTo(-0.25f, 0.13f, -0.5f, 0.25f, -0.77f, 0.34f);
        mPath.rLineTo(0f, 2.09f);
        mPath.rCubicTo(0.8f, -0.21f, 1.55f, -0.54f, 2.23f, -0.96f);
        mPath.rLineTo(2.36f, 2.36f);
        mPath.rLineTo(1.27f, -1.27f);
        mPath.lineTo(4.14f, 4.14f);
        mPath.lineTo(2.86f, 5.41f);
        mPath.close();
        mPath.moveTo(2.8600001f, 5.41f);
        mPath.moveTo(20.0f, 4.0f);
        mPath.rLineTo(-6.0f, 0f);
        mPath.rLineTo(0f, 6.0f);
        mPath.rLineTo(2.24f, -2.24f);
        mPath.cubicTo(17.32f, 8.85f, 18.0f, 10.34f, 18.0f, 12.0f);
        mPath.rCubicTo(0.0f, 1.0f, -0.25f, 1.94f, -0.68f, 2.77f);
        mPath.rLineTo(1.46f, 1.46f);
        mPath.cubicTo(19.55f, 15.01f, 20.0f, 13.56f, 20.0f, 12.0f);
        mPath.rCubicTo(0.0f, -2.21f, -0.91f, -4.2f, -2.36f, -5.64f);
        mPath.lineTo(20.0f, 4.0f);
        mPath.close();
        mPath.moveTo(20.0f, 4.0f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        if (mFillPaint == null) {
            mFillPaint = new Paint();
            mFillPaint.setStyle(Paint.Style.FILL);
            mFillPaint.setAntiAlias(true);
        }
        mFillPaint.setColor(applyAlpha(-16777216, 1.0f));
        mFillPaint.setColorFilter(filter);
        canvas.drawPath(mRenderPath, mFillPaint);

    }

}