package com.github.megatronking.svg.iconlibs;

import android.content.Context;
import android.graphics.Canvas;
import android.graphics.ColorFilter;
import android.graphics.Paint;

import com.github.megatronking.svg.support.SVGRenderer;

/**
 * AUTO-GENERATED FILE.  DO NOT MODIFY.
 * 
 * This class was automatically generated by the
 * SVG-Generator. It should not be modified by hand.
 */
public class ic_tap_and_play extends SVGRenderer {

    public ic_tap_and_play(Context context) {
        super(context);
        mAlpha = 1.0f;
        mWidth = dip2px(24.0f);
        mHeight = dip2px(24.0f);
    }

    @Override
    public void render(Canvas canvas, int w, int h, ColorFilter filter) {
        final float scaleX = w / 24.0f;
        final float scaleY = h / 24.0f;
        
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(2.0f, 16.0f);
        mPath.rLineTo(0f, 2.0f);
        mPath.rCubicTo(2.76f, 0.0f, 5.0f, 2.24f, 5.0f, 5.0f);
        mPath.rLineTo(2.0f, 0f);
        mPath.rCubicTo(0.0f, -3.87f, -3.13f, -7.0f, -7.0f, -7.0f);
        mPath.close();
        mPath.moveTo(2.0f, 16.0f);
        mPath.rMoveTo(0.0f, 4.0f);
        mPath.rLineTo(0f, 3.0f);
        mPath.rLineTo(3.0f, 0f);
        mPath.rCubicTo(0.0f, -1.66f, -1.34f, -3.0f, -3.0f, -3.0f);
        mPath.close();
        mPath.moveTo(2.0f, 20.0f);
        mPath.rMoveTo(0.0f, -8.0f);
        mPath.rLineTo(0f, 2.0f);
        mPath.rCubicTo(4.97f, 0.0f, 9.0f, 4.03f, 9.0f, 9.0f);
        mPath.rLineTo(2.0f, 0f);
        mPath.rCubicTo(0.0f, -6.08f, -4.92f, -11.0f, -11.0f, -11.0f);
        mPath.close();
        mPath.moveTo(2.0f, 12.0f);
        mPath.moveTo(17.0f, 1.01f);
        mPath.lineTo(7.0f, 1.0f);
        mPath.rCubicTo(-1.1f, 0.0f, -2.0f, 0.9f, -2.0f, 2.0f);
        mPath.rLineTo(0f, 7.37f);
        mPath.rCubicTo(0.69f, 0.16f, 1.36f, 0.37f, 2.0f, 0.64f);
        mPath.lineTo(7.0f, 5.0f);
        mPath.rLineTo(10.0f, 0f);
        mPath.rLineTo(0f, 13.0f);
        mPath.rLineTo(-3.03f, 0f);
        mPath.rCubicTo(0.52f, 1.25f, 0.84f, 2.59f, 0.95f, 4.0f);
        mPath.lineTo(17.0f, 22.0f);
        mPath.rCubicTo(1.1f, 0.0f, 2.0f, -0.9f, 2.0f, -2.0f);
        mPath.lineTo(19.0f, 3.0f);
        mPath.rCubicTo(0.0f, -1.1f, -0.9f, -1.99f, -2.0f, -1.99f);
        mPath.close();
        mPath.moveTo(17.0f, 1.01f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        if (mFillPaint == null) {
            mFillPaint = new Paint();
            mFillPaint.setStyle(Paint.Style.FILL);
            mFillPaint.setAntiAlias(true);
        }
        mFillPaint.setColor(applyAlpha(-16777216, 1.0f));
        mFillPaint.setColorFilter(filter);
        canvas.drawPath(mRenderPath, mFillPaint);

    }

}