package com.github.megatronking.svg.iconlibs;

import android.content.Context;
import android.graphics.Canvas;
import android.graphics.ColorFilter;
import android.graphics.Paint;

import com.github.megatronking.svg.support.SVGRenderer;

/**
 * AUTO-GENERATED FILE.  DO NOT MODIFY.
 * 
 * This class was automatically generated by the
 * SVG-Generator. It should not be modified by hand.
 */
public class ic_person_outline extends SVGRenderer {

    public ic_person_outline(Context context) {
        super(context);
        mAlpha = 1.0f;
        mWidth = dip2px(24.0f);
        mHeight = dip2px(24.0f);
    }

    @Override
    public void render(Canvas canvas, int w, int h, ColorFilter filter) {
        final float scaleX = w / 24.0f;
        final float scaleY = h / 24.0f;
        
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(12.0f, 5.9f);
        mPath.rCubicTo(1.16f, 0.0f, 2.1f, 0.94f, 2.1f, 2.1f);
        mPath.rCubicTo(0.0f, 1.1599998f, -0.94f, 2.1f, -2.1f, 2.1f);
        mPath.cubicTo(10.839999f, 10.1f, 9.9f, 9.16f, 9.9f, 8.0f);
        mPath.rCubicTo(0.0f, -1.1599998f, 0.94f, -2.1f, 2.1f, -2.1f);
        mPath.rMoveTo(0.0f, 9.0f);
        mPath.rCubicTo(2.97f, 0.0f, 6.1f, 1.46f, 6.1f, 2.1f);
        mPath.rLineTo(0f, 1.1f);
        mPath.lineTo(5.9f, 18.1f);
        mPath.lineTo(5.9f, 17.0f);
        mPath.rCubicTo(0.0f, -0.64f, 3.13f, -2.1f, 6.1f, -2.1f);
        mPath.moveTo(12.0f, 4.0f);
        mPath.cubicTo(9.79f, 4.0f, 8.0f, 5.79f, 8.0f, 8.0f);
        mPath.rCubicTo(0.0f, 2.21f, 1.79f, 4.0f, 4.0f, 4.0f);
        mPath.rCubicTo(2.21f, 0.0f, 4.0f, -1.79f, 4.0f, -4.0f);
        mPath.rCubicTo(0.0f, -2.21f, -1.79f, -4.0f, -4.0f, -4.0f);
        mPath.close();
        mPath.moveTo(12.0f, 4.0f);
        mPath.rMoveTo(0.0f, 9.0f);
        mPath.rCubicTo(-2.67f, 0.0f, -8.0f, 1.34f, -8.0f, 4.0f);
        mPath.rLineTo(0f, 3.0f);
        mPath.rLineTo(16.0f, 0f);
        mPath.rLineTo(0f, -3.0f);
        mPath.rCubicTo(0.0f, -2.66f, -5.33f, -4.0f, -8.0f, -4.0f);
        mPath.close();
        mPath.moveTo(12.0f, 13.0f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        if (mFillPaint == null) {
            mFillPaint = new Paint();
            mFillPaint.setStyle(Paint.Style.FILL);
            mFillPaint.setAntiAlias(true);
        }
        mFillPaint.setColor(applyAlpha(-16777216, 1.0f));
        mFillPaint.setColorFilter(filter);
        canvas.drawPath(mRenderPath, mFillPaint);

    }

}