package com.github.megatronking.svg.iconlibs;

import android.content.Context;
import android.graphics.Canvas;
import android.graphics.ColorFilter;
import android.graphics.Paint;

import com.github.megatronking.svg.support.SVGRenderer;

/**
 * AUTO-GENERATED FILE.  DO NOT MODIFY.
 * 
 * This class was automatically generated by the
 * SVG-Generator. It should not be modified by hand.
 */
public class ic_sentiment_very_satisfied extends SVGRenderer {

    public ic_sentiment_very_satisfied(Context context) {
        super(context);
        mAlpha = 1.0f;
        mWidth = dip2px(24.0f);
        mHeight = dip2px(24.0f);
    }

    @Override
    public void render(Canvas canvas, int w, int h, ColorFilter filter) {
        final float scaleX = w / 24.0f;
        final float scaleY = h / 24.0f;
        
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(11.99f, 2.0f);
        mPath.cubicTo(6.47f, 2.0f, 2.0f, 6.47f, 2.0f, 12.0f);
        mPath.rCubicTo(0.0f, 5.53f, 4.47f, 10.0f, 9.99f, 10.0f);
        mPath.cubicTo(17.51f, 22.0f, 22.0f, 17.53f, 22.0f, 12.0f);
        mPath.cubicTo(22.0f, 6.4699993f, 17.52f, 2.0f, 11.99f, 2.0f);
        mPath.close();
        mPath.moveTo(11.99f, 2.0f);
        mPath.moveTo(12.0f, 20.0f);
        mPath.rCubicTo(-4.42f, 0.0f, -8.0f, -3.58f, -8.0f, -8.0f);
        mPath.rCubicTo(0.0f, -4.42f, 3.58f, -8.0f, 8.0f, -8.0f);
        mPath.rCubicTo(4.42f, 0.0f, 8.0f, 3.58f, 8.0f, 8.0f);
        mPath.rCubicTo(0.0f, 4.42f, -3.58f, 8.0f, -8.0f, 8.0f);
        mPath.close();
        mPath.moveTo(12.0f, 20.0f);
        mPath.rMoveTo(1.0f, -10.06f);
        mPath.lineTo(14.06f, 11.0f);
        mPath.rLineTo(1.06f, -1.06f);
        mPath.lineTo(16.18f, 11.0f);
        mPath.rLineTo(1.06f, -1.06f);
        mPath.rLineTo(-2.12f, -2.12f);
        mPath.close();
        mPath.moveTo(13.0f, 9.94f);
        mPath.rMoveTo(-4.12f, 0.0f);
        mPath.lineTo(9.94f, 11.0f);
        mPath.lineTo(11.0f, 9.94f);
        mPath.lineTo(8.88f, 7.82f);
        mPath.lineTo(6.76f, 9.94f);
        mPath.lineTo(7.82f, 11.0f);
        mPath.close();
        mPath.moveTo(8.88f, 9.94f);
        mPath.moveTo(12.0f, 17.5f);
        mPath.rCubicTo(2.33f, 0.0f, 4.31f, -1.46f, 5.11f, -3.5f);
        mPath.lineTo(6.89f, 14.0f);
        mPath.rCubicTo(0.8f, 2.04f, 2.78f, 3.5f, 5.11f, 3.5f);
        mPath.close();
        mPath.moveTo(12.0f, 17.5f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        if (mFillPaint == null) {
            mFillPaint = new Paint();
            mFillPaint.setStyle(Paint.Style.FILL);
            mFillPaint.setAntiAlias(true);
        }
        mFillPaint.setColor(applyAlpha(-16777216, 1.0f));
        mFillPaint.setColorFilter(filter);
        canvas.drawPath(mRenderPath, mFillPaint);

    }

}