package com.github.megatronking.svg.iconlibs;

import android.content.Context;
import android.graphics.Canvas;
import android.graphics.ColorFilter;
import android.graphics.Paint;

import com.github.megatronking.svg.support.SVGRenderer;

/**
 * AUTO-GENERATED FILE.  DO NOT MODIFY.
 * 
 * This class was automatically generated by the
 * SVG-Generator. It should not be modified by hand.
 */
public class ic_add_alert extends SVGRenderer {

    public ic_add_alert(Context context) {
        super(context);
        mAlpha = 1.0f;
        mWidth = dip2px(24.0f);
        mHeight = dip2px(24.0f);
    }

    @Override
    public void render(Canvas canvas, int w, int h, ColorFilter filter) {
        final float scaleX = w / 24.0f;
        final float scaleY = h / 24.0f;
        
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(10.01f, 21.01f);
        mPath.rCubicTo(0.0f, 1.1f, 0.89f, 1.99f, 1.99f, 1.99f);
        mPath.rCubicTo(1.0999994f, 0.0f, 1.99f, -0.89f, 1.99f, -1.99f);
        mPath.rLineTo(-3.98f, 0f);
        mPath.close();
        mPath.moveTo(10.01f, 21.01f);
        mPath.rMoveTo(8.87f, -4.19f);
        mPath.lineTo(18.880001f, 11.0f);
        mPath.rCubicTo(0.0f, -3.25f, -2.25f, -5.97f, -5.29f, -6.69f);
        mPath.rLineTo(0f, -0.72f);
        mPath.cubicTo(13.59f, 2.71f, 12.88f, 2.0f, 12.0f, 2.0f);
        mPath.rCubicTo(-0.8800001f, 0.0f, -1.59f, 0.71f, -1.59f, 1.59f);
        mPath.rLineTo(0f, 0.72f);
        mPath.cubicTo(7.37f, 5.03f, 5.12f, 7.75f, 5.12f, 11.0f);
        mPath.rLineTo(0f, 5.82f);
        mPath.lineTo(3.0f, 18.94f);
        mPath.lineTo(3.0f, 20.0f);
        mPath.rLineTo(18.0f, 0f);
        mPath.rLineTo(0f, -1.06f);
        mPath.rLineTo(-2.12f, -2.12f);
        mPath.close();
        mPath.moveTo(18.880001f, 16.82f);
        mPath.moveTo(16.0f, 13.01f);
        mPath.rLineTo(-3.0f, 0f);
        mPath.rLineTo(0f, 3.0f);
        mPath.rLineTo(-2.0f, 0f);
        mPath.rLineTo(0f, -3.0f);
        mPath.lineTo(8.0f, 13.01f);
        mPath.lineTo(8.0f, 11.0f);
        mPath.rLineTo(3.0f, 0f);
        mPath.lineTo(11.0f, 8.0f);
        mPath.rLineTo(2.0f, 0f);
        mPath.rLineTo(0f, 3.0f);
        mPath.rLineTo(3.0f, 0f);
        mPath.rLineTo(0f, 2.01f);
        mPath.close();
        mPath.moveTo(16.0f, 13.01f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        if (mFillPaint == null) {
            mFillPaint = new Paint();
            mFillPaint.setStyle(Paint.Style.FILL);
            mFillPaint.setAntiAlias(true);
        }
        mFillPaint.setColor(applyAlpha(-16777216, 1.0f));
        mFillPaint.setColorFilter(filter);
        canvas.drawPath(mRenderPath, mFillPaint);

    }

}