package com.github.megatronking.svg.iconlibs;

import android.content.Context;
import android.graphics.Canvas;
import android.graphics.ColorFilter;
import android.graphics.Paint;

import com.github.megatronking.svg.support.SVGRenderer;

/**
 * AUTO-GENERATED FILE.  DO NOT MODIFY.
 * 
 * This class was automatically generated by the
 * SVG-Generator. It should not be modified by hand.
 */
public class ic_speaker_group extends SVGRenderer {

    public ic_speaker_group(Context context) {
        super(context);
        mAlpha = 1.0f;
        mWidth = dip2px(24.0f);
        mHeight = dip2px(24.0f);
    }

    @Override
    public void render(Canvas canvas, int w, int h, ColorFilter filter) {
        final float scaleX = w / 24.0f;
        final float scaleY = h / 24.0f;
        
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(18.2f, 1.0f);
        mPath.lineTo(9.8f, 1.0f);
        mPath.cubicTo(8.81f, 1.0f, 8.0f, 1.81f, 8.0f, 2.8f);
        mPath.rLineTo(0f, 14.4f);
        mPath.rCubicTo(0.0f, 0.99f, 0.81f, 1.79f, 1.8f, 1.79f);
        mPath.rLineTo(8.4f, 0.01f);
        mPath.rCubicTo(0.99f, 0.0f, 1.8f, -0.81f, 1.8f, -1.8f);
        mPath.lineTo(20.0f, 2.8f);
        mPath.rCubicTo(0.0f, -0.99f, -0.81f, -1.8f, -1.8f, -1.8f);
        mPath.close();
        mPath.moveTo(18.2f, 1.0f);
        mPath.moveTo(14.0f, 3.0f);
        mPath.rCubicTo(1.1f, 0.0f, 2.0f, 0.89f, 2.0f, 2.0f);
        mPath.rCubicTo(0.0f, 1.1100001f, -0.9f, 2.0f, -2.0f, 2.0f);
        mPath.rCubicTo(-1.1000004f, 0.0f, -2.0f, -0.89f, -2.0f, -2.0f);
        mPath.rCubicTo(0.0f, -1.1100001f, 0.9f, -2.0f, 2.0f, -2.0f);
        mPath.close();
        mPath.moveTo(14.0f, 3.0f);
        mPath.rMoveTo(0.0f, 13.5f);
        mPath.rCubicTo(-2.21f, 0.0f, -4.0f, -1.79f, -4.0f, -4.0f);
        mPath.rCubicTo(0.0f, -2.21f, 1.79f, -4.0f, 4.0f, -4.0f);
        mPath.rCubicTo(2.21f, 0.0f, 4.0f, 1.79f, 4.0f, 4.0f);
        mPath.rCubicTo(0.0f, 2.21f, -1.79f, 4.0f, -4.0f, 4.0f);
        mPath.close();
        mPath.moveTo(14.0f, 16.5f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        if (mFillPaint == null) {
            mFillPaint = new Paint();
            mFillPaint.setStyle(Paint.Style.FILL);
            mFillPaint.setAntiAlias(true);
        }
        mFillPaint.setColor(applyAlpha(-16777216, 1.0f));
        mFillPaint.setColorFilter(filter);
        canvas.drawPath(mRenderPath, mFillPaint);
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(14.0f, 12.5f);
        mPath.rMoveTo(-2.5f, 0.0f);
        mPath.cubicTo(11.5f, 11.8372135f, 11.763572f, 11.200894f, 12.232233f, 10.732233f);
        mPath.cubicTo(12.700894f, 10.263572f, 13.3372135f, 10.0f, 14.0f, 10.0f);
        mPath.cubicTo(14.6627865f, 10.0f, 15.299106f, 10.263572f, 15.767767f, 10.732233f);
        mPath.cubicTo(16.236427f, 11.200894f, 16.5f, 11.8372135f, 16.5f, 12.5f);
        mPath.cubicTo(16.5f, 13.1627865f, 16.236427f, 13.799106f, 15.767767f, 14.267767f);
        mPath.cubicTo(15.299106f, 14.736428f, 14.6627865f, 15.0f, 14.0f, 15.0f);
        mPath.cubicTo(13.3372135f, 15.0f, 12.700894f, 14.736428f, 12.232233f, 14.267767f);
        mPath.cubicTo(11.763572f, 13.799106f, 11.5f, 13.1627865f, 11.5f, 12.5f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        mFillPaint.setColor(applyAlpha(-16777216, 1.0f));
        mFillPaint.setColorFilter(filter);
        canvas.drawPath(mRenderPath, mFillPaint);
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(6.0f, 5.0f);
        mPath.lineTo(4.0f, 5.0f);
        mPath.rLineTo(0f, 16.0f);
        mPath.rCubicTo(0.0f, 1.1f, 0.89f, 2.0f, 2.0f, 2.0f);
        mPath.rLineTo(10.0f, 0f);
        mPath.rLineTo(0f, -2.0f);
        mPath.lineTo(6.0f, 21.0f);
        mPath.lineTo(6.0f, 5.0f);
        mPath.close();
        mPath.moveTo(6.0f, 5.0f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        mFillPaint.setColor(applyAlpha(-16777216, 1.0f));
        mFillPaint.setColorFilter(filter);
        canvas.drawPath(mRenderPath, mFillPaint);

    }

}