package com.github.megatronking.svg.iconlibs;

import android.content.Context;
import android.graphics.Canvas;
import android.graphics.ColorFilter;
import android.graphics.Paint;

import com.github.megatronking.svg.support.SVGRenderer;

/**
 * AUTO-GENERATED FILE.  DO NOT MODIFY.
 * 
 * This class was automatically generated by the
 * SVG-Generator. It should not be modified by hand.
 */
public class ic_bluetooth_connected extends SVGRenderer {

    public ic_bluetooth_connected(Context context) {
        super(context);
        mAlpha = 1.0f;
        mWidth = dip2px(24.0f);
        mHeight = dip2px(24.0f);
    }

    @Override
    public void render(Canvas canvas, int w, int h, ColorFilter filter) {
        final float scaleX = w / 24.0f;
        final float scaleY = h / 24.0f;
        
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(7.0f, 12.0f);
        mPath.rLineTo(-2.0f, -2.0f);
        mPath.rLineTo(-2.0f, 2.0f);
        mPath.rLineTo(2.0f, 2.0f);
        mPath.rLineTo(2.0f, -2.0f);
        mPath.close();
        mPath.moveTo(7.0f, 12.0f);
        mPath.rMoveTo(10.71f, -4.29f);
        mPath.lineTo(12.0f, 2.0f);
        mPath.rLineTo(-1.0f, 0f);
        mPath.rLineTo(0f, 7.59f);
        mPath.lineTo(6.41f, 5.0f);
        mPath.lineTo(5.0f, 6.41f);
        mPath.lineTo(10.59f, 12.0f);
        mPath.lineTo(5.0f, 17.59f);
        mPath.lineTo(6.41f, 19.0f);
        mPath.lineTo(11.0f, 14.41f);
        mPath.lineTo(11.0f, 22.0f);
        mPath.rLineTo(1.0f, 0f);
        mPath.rLineTo(5.71f, -5.71f);
        mPath.rLineTo(-4.3f, -4.29f);
        mPath.rLineTo(4.3f, -4.29f);
        mPath.close();
        mPath.moveTo(17.71f, 7.71f);
        mPath.moveTo(13.0f, 5.83f);
        mPath.rLineTo(1.88f, 1.88f);
        mPath.lineTo(13.0f, 9.59f);
        mPath.lineTo(13.0f, 5.83f);
        mPath.close();
        mPath.moveTo(13.0f, 5.83f);
        mPath.rMoveTo(1.88f, 10.46f);
        mPath.lineTo(13.0f, 18.17f);
        mPath.rLineTo(0f, -3.76f);
        mPath.rLineTo(1.88f, 1.88f);
        mPath.close();
        mPath.moveTo(14.88f, 16.29f);
        mPath.moveTo(19.0f, 10.0f);
        mPath.rLineTo(-2.0f, 2.0f);
        mPath.rLineTo(2.0f, 2.0f);
        mPath.rLineTo(2.0f, -2.0f);
        mPath.rLineTo(-2.0f, -2.0f);
        mPath.close();
        mPath.moveTo(19.0f, 10.0f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        if (mFillPaint == null) {
            mFillPaint = new Paint();
            mFillPaint.setStyle(Paint.Style.FILL);
            mFillPaint.setAntiAlias(true);
        }
        mFillPaint.setColor(applyAlpha(-16777216, 1.0f));
        mFillPaint.setColorFilter(filter);
        canvas.drawPath(mRenderPath, mFillPaint);

    }

}