package com.github.megatronking.svg.iconlibs;

import android.content.Context;
import android.graphics.Canvas;
import android.graphics.ColorFilter;
import android.graphics.Paint;

import com.github.megatronking.svg.support.SVGRenderer;

/**
 * AUTO-GENERATED FILE.  DO NOT MODIFY.
 * 
 * This class was automatically generated by the
 * SVG-Generator. It should not be modified by hand.
 */
public class ic_usb extends SVGRenderer {

    public ic_usb(Context context) {
        super(context);
        mAlpha = 1.0f;
        mWidth = dip2px(24.0f);
        mHeight = dip2px(24.0f);
    }

    @Override
    public void render(Canvas canvas, int w, int h, ColorFilter filter) {
        final float scaleX = w / 24.0f;
        final float scaleY = h / 24.0f;
        
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(15.0f, 7.0f);
        mPath.rLineTo(0f, 4.0f);
        mPath.rLineTo(1.0f, 0f);
        mPath.rLineTo(0f, 2.0f);
        mPath.rLineTo(-3.0f, 0f);
        mPath.lineTo(13.0f, 5.0f);
        mPath.rLineTo(2.0f, 0f);
        mPath.rLineTo(-3.0f, -4.0f);
        mPath.rLineTo(-3.0f, 4.0f);
        mPath.rLineTo(2.0f, 0f);
        mPath.rLineTo(0f, 8.0f);
        mPath.lineTo(8.0f, 13.0f);
        mPath.rLineTo(0f, -2.07f);
        mPath.rCubicTo(0.7f, -0.37f, 1.2f, -1.08f, 1.2f, -1.93f);
        mPath.rCubicTo(0.0f, -1.21f, -0.99f, -2.2f, -2.2f, -2.2f);
        mPath.rCubicTo(-1.21f, 0.0f, -2.2f, 0.99f, -2.2f, 2.2f);
        mPath.rCubicTo(0.0f, 0.85f, 0.5f, 1.56f, 1.2f, 1.93f);
        mPath.lineTo(6.0f, 13.0f);
        mPath.rCubicTo(0.0f, 1.11f, 0.89f, 2.0f, 2.0f, 2.0f);
        mPath.rLineTo(3.0f, 0f);
        mPath.rLineTo(0f, 3.05f);
        mPath.rCubicTo(-0.71f, 0.37f, -1.2f, 1.1f, -1.2f, 1.95f);
        mPath.rCubicTo(0.0f, 1.22f, 0.99f, 2.2f, 2.2f, 2.2f);
        mPath.rCubicTo(1.21f, 0.0f, 2.2f, -0.98f, 2.2f, -2.2f);
        mPath.rCubicTo(0.0f, -0.85f, -0.49f, -1.58f, -1.2f, -1.95f);
        mPath.lineTo(13.0f, 15.0f);
        mPath.rLineTo(3.0f, 0f);
        mPath.rCubicTo(1.11f, 0.0f, 2.0f, -0.89f, 2.0f, -2.0f);
        mPath.rLineTo(0f, -2.0f);
        mPath.rLineTo(1.0f, 0f);
        mPath.lineTo(19.0f, 7.0f);
        mPath.rLineTo(-4.0f, 0f);
        mPath.close();
        mPath.moveTo(15.0f, 7.0f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        if (mFillPaint == null) {
            mFillPaint = new Paint();
            mFillPaint.setStyle(Paint.Style.FILL);
            mFillPaint.setAntiAlias(true);
        }
        mFillPaint.setColor(applyAlpha(-16777216, 1.0f));
        mFillPaint.setColorFilter(filter);
        canvas.drawPath(mRenderPath, mFillPaint);

    }

}