package com.github.megatronking.svg.iconlibs;

import android.content.Context;
import android.graphics.Canvas;
import android.graphics.ColorFilter;
import android.graphics.Paint;

import com.github.megatronking.svg.support.SVGRenderer;

/**
 * AUTO-GENERATED FILE.  DO NOT MODIFY.
 * 
 * This class was automatically generated by the
 * SVG-Generator. It should not be modified by hand.
 */
public class ic_widgets extends SVGRenderer {

    public ic_widgets(Context context) {
        super(context);
        mAlpha = 1.0f;
        mWidth = dip2px(24.0f);
        mHeight = dip2px(24.0f);
    }

    @Override
    public void render(Canvas canvas, int w, int h, ColorFilter filter) {
        final float scaleX = w / 24.0f;
        final float scaleY = h / 24.0f;
        
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(13.0f, 13.0f);
        mPath.rLineTo(0f, 8.0f);
        mPath.rLineTo(8.0f, 0f);
        mPath.rLineTo(0f, -8.0f);
        mPath.rLineTo(-8.0f, 0f);
        mPath.close();
        mPath.moveTo(13.0f, 13.0f);
        mPath.moveTo(3.0f, 21.0f);
        mPath.rLineTo(8.0f, 0f);
        mPath.rLineTo(0f, -8.0f);
        mPath.lineTo(3.0f, 13.0f);
        mPath.rLineTo(0f, 8.0f);
        mPath.close();
        mPath.moveTo(3.0f, 21.0f);
        mPath.moveTo(3.0f, 3.0f);
        mPath.rLineTo(0f, 8.0f);
        mPath.rLineTo(8.0f, 0f);
        mPath.lineTo(11.0f, 3.0f);
        mPath.lineTo(3.0f, 3.0f);
        mPath.close();
        mPath.moveTo(3.0f, 3.0f);
        mPath.rMoveTo(13.66f, -1.31f);
        mPath.lineTo(11.0f, 7.34f);
        mPath.lineTo(16.66f, 13.0f);
        mPath.rLineTo(5.66f, -5.66f);
        mPath.rLineTo(-5.66f, -5.65f);
        mPath.close();
        mPath.moveTo(16.66f, 1.69f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        if (mFillPaint == null) {
            mFillPaint = new Paint();
            mFillPaint.setStyle(Paint.Style.FILL);
            mFillPaint.setAntiAlias(true);
        }
        mFillPaint.setColor(applyAlpha(-16777216, 1.0f));
        mFillPaint.setColorFilter(filter);
        canvas.drawPath(mRenderPath, mFillPaint);

    }

}