package com.github.megatronking.svg.iconlibs;

import android.content.Context;
import android.graphics.Canvas;
import android.graphics.ColorFilter;
import android.graphics.Paint;

import com.github.megatronking.svg.support.SVGRenderer;

/**
 * AUTO-GENERATED FILE.  DO NOT MODIFY.
 * 
 * This class was automatically generated by the
 * SVG-Generator. It should not be modified by hand.
 */
public class ic_format_bold extends SVGRenderer {

    public ic_format_bold(Context context) {
        super(context);
        mAlpha = 1.0f;
        mWidth = dip2px(24.0f);
        mHeight = dip2px(24.0f);
    }

    @Override
    public void render(Canvas canvas, int w, int h, ColorFilter filter) {
        final float scaleX = w / 24.0f;
        final float scaleY = h / 24.0f;
        
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(15.6f, 10.79f);
        mPath.rCubicTo(0.97f, -0.67f, 1.65f, -1.77f, 1.65f, -2.79f);
        mPath.rCubicTo(0.0f, -2.26f, -1.75f, -4.0f, -4.0f, -4.0f);
        mPath.lineTo(7.0f, 4.0f);
        mPath.rLineTo(0f, 14.0f);
        mPath.rLineTo(7.04f, 0f);
        mPath.rCubicTo(2.09f, 0.0f, 3.71f, -1.7f, 3.71f, -3.79f);
        mPath.rCubicTo(0.0f, -1.52f, -0.86f, -2.82f, -2.15f, -3.42f);
        mPath.close();
        mPath.moveTo(15.6f, 10.79f);
        mPath.moveTo(10.0f, 6.5f);
        mPath.rLineTo(3.0f, 0f);
        mPath.rCubicTo(0.83f, 0.0f, 1.5f, 0.67f, 1.5f, 1.5f);
        mPath.rCubicTo(0.0f, 0.8299999f, -0.67f, 1.5f, -1.5f, 1.5f);
        mPath.rLineTo(-3.0f, 0f);
        mPath.rLineTo(0f, -3.0f);
        mPath.close();
        mPath.moveTo(10.0f, 6.5f);
        mPath.rMoveTo(3.5f, 9.0f);
        mPath.lineTo(10.0f, 15.5f);
        mPath.rLineTo(0f, -3.0f);
        mPath.rLineTo(3.5f, 0f);
        mPath.rCubicTo(0.83f, 0.0f, 1.5f, 0.67f, 1.5f, 1.5f);
        mPath.rCubicTo(0.0f, 0.8299999f, -0.67f, 1.5f, -1.5f, 1.5f);
        mPath.close();
        mPath.moveTo(13.5f, 15.5f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        if (mFillPaint == null) {
            mFillPaint = new Paint();
            mFillPaint.setStyle(Paint.Style.FILL);
            mFillPaint.setAntiAlias(true);
        }
        mFillPaint.setColor(applyAlpha(-16777216, 1.0f));
        mFillPaint.setColorFilter(filter);
        canvas.drawPath(mRenderPath, mFillPaint);

    }

}