package com.github.megatronking.svg.iconlibs;

import android.content.Context;
import android.graphics.Canvas;
import android.graphics.ColorFilter;
import android.graphics.Paint;

import com.github.megatronking.svg.support.SVGRenderer;

/**
 * AUTO-GENERATED FILE.  DO NOT MODIFY.
 * 
 * This class was automatically generated by the
 * SVG-Generator. It should not be modified by hand.
 */
public class ic_monetization_on extends SVGRenderer {

    public ic_monetization_on(Context context) {
        super(context);
        mAlpha = 1.0f;
        mWidth = dip2px(24.0f);
        mHeight = dip2px(24.0f);
    }

    @Override
    public void render(Canvas canvas, int w, int h, ColorFilter filter) {
        final float scaleX = w / 24.0f;
        final float scaleY = h / 24.0f;
        
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(12.0f, 2.0f);
        mPath.cubicTo(6.48f, 2.0f, 2.0f, 6.48f, 2.0f, 12.0f);
        mPath.rCubicTo(0.0f, 5.52f, 4.48f, 10.0f, 10.0f, 10.0f);
        mPath.rCubicTo(5.52f, 0.0f, 10.0f, -4.48f, 10.0f, -10.0f);
        mPath.cubicTo(22.0f, 6.4799995f, 17.52f, 2.0f, 12.0f, 2.0f);
        mPath.close();
        mPath.moveTo(12.0f, 2.0f);
        mPath.rMoveTo(1.41f, 16.09f);
        mPath.lineTo(13.41f, 20.0f);
        mPath.rLineTo(-2.67f, 0f);
        mPath.rLineTo(0f, -1.93f);
        mPath.rCubicTo(-1.71f, -0.36f, -3.16f, -1.46f, -3.27f, -3.4f);
        mPath.rLineTo(1.96f, 0f);
        mPath.rCubicTo(0.1f, 1.05f, 0.82f, 1.87f, 2.65f, 1.87f);
        mPath.rCubicTo(1.96f, 0.0f, 2.4f, -0.98f, 2.4f, -1.59f);
        mPath.rCubicTo(0.0f, -0.83f, -0.44f, -1.61f, -2.67f, -2.14f);
        mPath.rCubicTo(-2.48f, -0.6f, -4.18f, -1.62f, -4.18f, -3.67f);
        mPath.rCubicTo(0.0f, -1.72f, 1.39f, -2.84f, 3.11f, -3.21f);
        mPath.lineTo(10.74f, 4.0f);
        mPath.rLineTo(2.67f, 0f);
        mPath.rLineTo(0f, 1.95f);
        mPath.rCubicTo(1.86f, 0.45f, 2.79f, 1.86f, 2.85f, 3.39f);
        mPath.lineTo(14.3f, 9.34f);
        mPath.rCubicTo(-0.05f, -1.11f, -0.64f, -1.87f, -2.22f, -1.87f);
        mPath.rCubicTo(-1.5f, 0.0f, -2.4f, 0.68f, -2.4f, 1.64f);
        mPath.rCubicTo(0.0f, 0.84f, 0.65f, 1.39f, 2.67f, 1.91f);
        mPath.rCubicTo(2.0200005f, 0.5199995f, 4.18f, 1.39f, 4.18f, 3.91f);
        mPath.rCubicTo(-0.01f, 1.83f, -1.38f, 2.83f, -3.12f, 3.16f);
        mPath.close();
        mPath.moveTo(13.41f, 18.09f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        if (mFillPaint == null) {
            mFillPaint = new Paint();
            mFillPaint.setStyle(Paint.Style.FILL);
            mFillPaint.setAntiAlias(true);
        }
        mFillPaint.setColor(applyAlpha(-16777216, 1.0f));
        mFillPaint.setColorFilter(filter);
        canvas.drawPath(mRenderPath, mFillPaint);

    }

}