package com.github.megatronking.svg.iconlibs;

import android.content.Context;
import android.graphics.Canvas;
import android.graphics.ColorFilter;
import android.graphics.Paint;

import com.github.megatronking.svg.support.SVGRenderer;

/**
 * AUTO-GENERATED FILE.  DO NOT MODIFY.
 * 
 * This class was automatically generated by the
 * SVG-Generator. It should not be modified by hand.
 */
public class ic_all_inclusive extends SVGRenderer {

    public ic_all_inclusive(Context context) {
        super(context);
        mAlpha = 1.0f;
        mWidth = dip2px(24.0f);
        mHeight = dip2px(24.0f);
    }

    @Override
    public void render(Canvas canvas, int w, int h, ColorFilter filter) {
        final float scaleX = w / 24.0f;
        final float scaleY = h / 24.0f;
        
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(18.6f, 6.62f);
        mPath.rCubicTo(-1.44f, 0.0f, -2.8f, 0.56f, -3.77f, 1.53f);
        mPath.lineTo(12.0f, 10.66f);
        mPath.lineTo(10.48f, 12.0f);
        mPath.rLineTo(0.01f, 0f);
        mPath.lineTo(7.8f, 14.39f);
        mPath.rCubicTo(-0.64f, 0.64f, -1.49f, 0.99f, -2.4f, 0.99f);
        mPath.rCubicTo(-1.87f, 0.0f, -3.39f, -1.51f, -3.39f, -3.38f);
        mPath.cubicTo(2.01f, 10.13f, 3.53f, 8.62f, 5.4f, 8.62f);
        mPath.rCubicTo(0.91f, 0.0f, 1.76f, 0.35f, 2.44f, 1.03f);
        mPath.rLineTo(1.13f, 1.0f);
        mPath.rLineTo(1.51f, -1.34f);
        mPath.lineTo(9.22f, 8.2f);
        mPath.cubicTo(8.2f, 7.18f, 6.84f, 6.62f, 5.4f, 6.62f);
        mPath.cubicTo(2.42f, 6.62f, 0.0f, 9.04f, 0.0f, 12.0f);
        mPath.rCubicTo(0.0f, 2.96f, 2.42f, 5.38f, 5.4f, 5.38f);
        mPath.rCubicTo(1.44f, 0.0f, 2.8f, -0.56f, 3.77f, -1.53f);
        mPath.rLineTo(2.83f, -2.5f);
        mPath.rLineTo(0.01f, 0.01f);
        mPath.lineTo(13.52f, 12.0f);
        mPath.rLineTo(-0.01f, 0f);
        mPath.rLineTo(2.69f, -2.39f);
        mPath.rCubicTo(0.64f, -0.64f, 1.49f, -0.99f, 2.4f, -0.99f);
        mPath.rCubicTo(1.87f, 0.0f, 3.39f, 1.51f, 3.39f, 3.38f);
        mPath.rCubicTo(0.0f, 1.8699999f, -1.52f, 3.38f, -3.39f, 3.38f);
        mPath.rCubicTo(-0.9f, 0.0f, -1.76f, -0.35f, -2.44f, -1.03f);
        mPath.rLineTo(-1.14f, -1.01f);
        mPath.rLineTo(-1.51f, 1.34f);
        mPath.rLineTo(1.27f, 1.12f);
        mPath.rCubicTo(1.02f, 1.01f, 2.37f, 1.57f, 3.82f, 1.57f);
        mPath.rCubicTo(2.98f, 0.0f, 5.4f, -2.41f, 5.4f, -5.38f);
        mPath.rCubicTo(0.0f, -2.9700003f, -2.42f, -5.37f, -5.4f, -5.37f);
        mPath.close();
        mPath.moveTo(18.6f, 6.62f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        if (mFillPaint == null) {
            mFillPaint = new Paint();
            mFillPaint.setStyle(Paint.Style.FILL);
            mFillPaint.setAntiAlias(true);
        }
        mFillPaint.setColor(applyAlpha(-16777216, 1.0f));
        mFillPaint.setColorFilter(filter);
        canvas.drawPath(mRenderPath, mFillPaint);

    }

}