package com.github.megatronking.svg.iconlibs;

import android.content.Context;
import android.graphics.Canvas;
import android.graphics.ColorFilter;
import android.graphics.Paint;

import com.github.megatronking.svg.support.SVGRenderer;

/**
 * AUTO-GENERATED FILE.  DO NOT MODIFY.
 * 
 * This class was automatically generated by the
 * SVG-Generator. It should not be modified by hand.
 */
public class ic_beach_access extends SVGRenderer {

    public ic_beach_access(Context context) {
        super(context);
        mAlpha = 1.0f;
        mWidth = dip2px(24.0f);
        mHeight = dip2px(24.0f);
    }

    @Override
    public void render(Canvas canvas, int w, int h, ColorFilter filter) {
        final float scaleX = w / 24.0f;
        final float scaleY = h / 24.0f;
        
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(13.127f, 14.56f);
        mPath.rLineTo(1.43f, -1.43f);
        mPath.rLineTo(6.44f, 6.443f);
        mPath.lineTo(19.57f, 21.0f);
        mPath.close();
        mPath.moveTo(13.127f, 14.56f);
        mPath.rMoveTo(4.293f, -5.73f);
        mPath.rLineTo(2.86f, -2.86f);
        mPath.rCubicTo(-3.95f, -3.95f, -10.35f, -3.96f, -14.3f, -0.02f);
        mPath.rCubicTo(3.93f, -1.3f, 8.31f, -0.25f, 11.44f, 2.88f);
        mPath.close();
        mPath.moveTo(17.42f, 8.83f);
        mPath.moveTo(5.95f, 5.98f);
        mPath.rCubicTo(-3.94f, 3.95f, -3.93f, 10.35f, 0.02f, 14.3f);
        mPath.rLineTo(2.86f, -2.86f);
        mPath.cubicTo(5.7f, 14.29f, 4.65f, 9.91f, 5.95f, 5.98f);
        mPath.close();
        mPath.moveTo(5.95f, 5.98f);
        mPath.rMoveTo(0.02f, -0.02f);
        mPath.rLineTo(-0.01f, 0.01f);
        mPath.rCubicTo(-0.38f, 3.01f, 1.17f, 6.88f, 4.3f, 10.02f);
        mPath.rLineTo(5.73f, -5.73f);
        mPath.rCubicTo(-3.13f, -3.13f, -7.01f, -4.68f, -10.02f, -4.3f);
        mPath.close();
        mPath.moveTo(5.97f, 5.96f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        if (mFillPaint == null) {
            mFillPaint = new Paint();
            mFillPaint.setStyle(Paint.Style.FILL);
            mFillPaint.setAntiAlias(true);
        }
        mFillPaint.setColor(applyAlpha(-16777216, 1.0f));
        mFillPaint.setColorFilter(filter);
        canvas.drawPath(mRenderPath, mFillPaint);

    }

}