package com.github.megatronking.svg.iconlibs;

import android.content.Context;
import android.graphics.Canvas;
import android.graphics.ColorFilter;
import android.graphics.Paint;

import com.github.megatronking.svg.support.SVGRenderer;

/**
 * AUTO-GENERATED FILE.  DO NOT MODIFY.
 * 
 * This class was automatically generated by the
 * SVG-Generator. It should not be modified by hand.
 */
public class ic_child_friendly extends SVGRenderer {

    public ic_child_friendly(Context context) {
        super(context);
        mAlpha = 1.0f;
        mWidth = dip2px(24.0f);
        mHeight = dip2px(24.0f);
    }

    @Override
    public void render(Canvas canvas, int w, int h, ColorFilter filter) {
        final float scaleX = w / 24.0f;
        final float scaleY = h / 24.0f;
        
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(13.0f, 2.0f);
        mPath.rLineTo(0f, 8.0f);
        mPath.rLineTo(8.0f, 0f);
        mPath.rCubicTo(0.0f, -4.42f, -3.58f, -8.0f, -8.0f, -8.0f);
        mPath.close();
        mPath.moveTo(13.0f, 2.0f);
        mPath.rMoveTo(6.32f, 13.89f);
        mPath.cubicTo(20.37f, 14.54f, 21.0f, 12.84f, 21.0f, 11.0f);
        mPath.lineTo(6.44f, 11.0f);
        mPath.rLineTo(-0.95f, -2.0f);
        mPath.lineTo(2.0f, 9.0f);
        mPath.rLineTo(0f, 2.0f);
        mPath.rLineTo(2.22f, 0f);
        mPath.rCubicTo(0.0f, 0.0f, 1.89f, 4.07f, 2.12f, 4.42f);
        mPath.rCubicTo(-1.1f, 0.59f, -1.84f, 1.75f, -1.84f, 3.08f);
        mPath.cubicTo(4.5f, 20.43f, 6.07f, 22.0f, 8.0f, 22.0f);
        mPath.rCubicTo(1.76f, 0.0f, 3.22f, -1.3f, 3.46f, -3.0f);
        mPath.rLineTo(2.08f, 0f);
        mPath.rCubicTo(0.24f, 1.7f, 1.7f, 3.0f, 3.46f, 3.0f);
        mPath.rCubicTo(1.93f, 0.0f, 3.5f, -1.57f, 3.5f, -3.5f);
        mPath.rCubicTo(0.0f, -1.04f, -0.46f, -1.97f, -1.18f, -2.61f);
        mPath.close();
        mPath.moveTo(19.32f, 15.89f);
        mPath.moveTo(8.0f, 20.0f);
        mPath.rCubicTo(-0.83f, 0.0f, -1.5f, -0.67f, -1.5f, -1.5f);
        mPath.cubicTo(6.5f, 17.67f, 7.17f, 17.0f, 8.0f, 17.0f);
        mPath.rCubicTo(0.8299999f, 0.0f, 1.5f, 0.67f, 1.5f, 1.5f);
        mPath.cubicTo(9.5f, 19.33f, 8.83f, 20.0f, 8.0f, 20.0f);
        mPath.close();
        mPath.moveTo(8.0f, 20.0f);
        mPath.rMoveTo(9.0f, 0.0f);
        mPath.rCubicTo(-0.83f, 0.0f, -1.5f, -0.67f, -1.5f, -1.5f);
        mPath.cubicTo(15.5f, 17.67f, 16.17f, 17.0f, 17.0f, 17.0f);
        mPath.rCubicTo(0.8299999f, 0.0f, 1.5f, 0.67f, 1.5f, 1.5f);
        mPath.cubicTo(18.5f, 19.33f, 17.83f, 20.0f, 17.0f, 20.0f);
        mPath.close();
        mPath.moveTo(17.0f, 20.0f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        if (mFillPaint == null) {
            mFillPaint = new Paint();
            mFillPaint.setStyle(Paint.Style.FILL);
            mFillPaint.setAntiAlias(true);
        }
        mFillPaint.setColor(applyAlpha(-16777216, 1.0f));
        mFillPaint.setColorFilter(filter);
        canvas.drawPath(mRenderPath, mFillPaint);

    }

}