package com.github.megatronking.svg.iconlibs;

import android.content.Context;
import android.graphics.Canvas;
import android.graphics.ColorFilter;
import android.graphics.Paint;

import com.github.megatronking.svg.support.SVGRenderer;

/**
 * AUTO-GENERATED FILE.  DO NOT MODIFY.
 * 
 * This class was automatically generated by the
 * SVG-Generator. It should not be modified by hand.
 */
public class ic_smoke_free extends SVGRenderer {

    public ic_smoke_free(Context context) {
        super(context);
        mAlpha = 1.0f;
        mWidth = dip2px(24.0f);
        mHeight = dip2px(24.0f);
    }

    @Override
    public void render(Canvas canvas, int w, int h, ColorFilter filter) {
        final float scaleX = w / 24.0f;
        final float scaleY = h / 24.0f;
        
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(2.0f, 6.0f);
        mPath.rLineTo(6.99f, 7.0f);
        mPath.lineTo(2.0f, 13.0f);
        mPath.rLineTo(0f, 3.0f);
        mPath.rLineTo(9.99f, 0f);
        mPath.rLineTo(7.0f, 7.0f);
        mPath.rLineTo(1.26f, -1.25f);
        mPath.rLineTo(-17.0f, -17.0f);
        mPath.close();
        mPath.moveTo(2.0f, 6.0f);
        mPath.rMoveTo(18.5f, 7.0f);
        mPath.lineTo(22.0f, 13.0f);
        mPath.rLineTo(0f, 3.0f);
        mPath.rLineTo(-1.5f, 0f);
        mPath.close();
        mPath.moveTo(20.5f, 13.0f);
        mPath.moveTo(18.0f, 13.0f);
        mPath.rLineTo(1.5f, 0f);
        mPath.rLineTo(0f, 3.0f);
        mPath.lineTo(18.0f, 16.0f);
        mPath.close();
        mPath.moveTo(18.0f, 13.0f);
        mPath.rMoveTo(0.85f, -8.12f);
        mPath.rCubicTo(0.62f, -0.61f, 1.0f, -1.45f, 1.0f, -2.38f);
        mPath.rLineTo(-1.5f, 0f);
        mPath.rCubicTo(0.0f, 1.02f, -0.83f, 1.85f, -1.85f, 1.85f);
        mPath.rLineTo(0f, 1.5f);
        mPath.rCubicTo(2.24f, 0.0f, 4.0f, 1.83f, 4.0f, 4.07f);
        mPath.lineTo(20.5f, 12.0f);
        mPath.lineTo(22.0f, 12.0f);
        mPath.lineTo(22.0f, 9.92f);
        mPath.rCubicTo(0.0f, -2.23f, -1.28f, -4.15f, -3.15f, -5.04f);
        mPath.close();
        mPath.moveTo(18.85f, 4.88f);
        mPath.moveTo(14.5f, 8.7f);
        mPath.rLineTo(1.53f, 0f);
        mPath.rCubicTo(1.05f, 0.0f, 1.97f, 0.74f, 1.97f, 2.05f);
        mPath.lineTo(18.0f, 12.0f);
        mPath.rLineTo(1.5f, 0f);
        mPath.rLineTo(0f, -1.59f);
        mPath.rCubicTo(0.0f, -1.8f, -1.6f, -3.16f, -3.47f, -3.16f);
        mPath.lineTo(14.5f, 7.25f);
        mPath.rCubicTo(-1.02f, 0.0f, -1.85f, -0.98f, -1.85f, -2.0f);
        mPath.rCubicTo(0.0f, -1.02f, 0.83f, -1.75f, 1.85f, -1.75f);
        mPath.lineTo(14.5f, 2.0f);
        mPath.rCubicTo(-1.85f, 0.0f, -3.35f, 1.5f, -3.35f, 3.35f);
        mPath.rCubicTo(0.0f, 1.8499999f, 1.5f, 3.35f, 3.35f, 3.35f);
        mPath.close();
        mPath.moveTo(14.5f, 8.7f);
        mPath.rMoveTo(2.5f, 7.23f);
        mPath.lineTo(17.0f, 13.0f);
        mPath.rLineTo(-2.93f, 0f);
        mPath.close();
        mPath.moveTo(17.0f, 15.93f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        if (mFillPaint == null) {
            mFillPaint = new Paint();
            mFillPaint.setStyle(Paint.Style.FILL);
            mFillPaint.setAntiAlias(true);
        }
        mFillPaint.setColor(applyAlpha(-16777216, 1.0f));
        mFillPaint.setColorFilter(filter);
        canvas.drawPath(mRenderPath, mFillPaint);

    }

}