package com.github.megatronking.svg.iconlibs;

import android.content.Context;
import android.graphics.Canvas;
import android.graphics.ColorFilter;
import android.graphics.Paint;

import com.github.megatronking.svg.support.SVGRenderer;

/**
 * AUTO-GENERATED FILE.  DO NOT MODIFY.
 * 
 * This class was automatically generated by the
 * SVG-Generator. It should not be modified by hand.
 */
public class ic_archive extends SVGRenderer {

    public ic_archive(Context context) {
        super(context);
        mAlpha = 1.0f;
        mWidth = dip2px(24.0f);
        mHeight = dip2px(24.0f);
    }

    @Override
    public void render(Canvas canvas, int w, int h, ColorFilter filter) {
        final float scaleX = w / 24.0f;
        final float scaleY = h / 24.0f;
        
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(20.54f, 5.23f);
        mPath.rLineTo(-1.39f, -1.68f);
        mPath.cubicTo(18.88f, 3.21f, 18.47f, 3.0f, 18.0f, 3.0f);
        mPath.lineTo(6.0f, 3.0f);
        mPath.rCubicTo(-0.47f, 0.0f, -0.88f, 0.21f, -1.16f, 0.55f);
        mPath.lineTo(3.46f, 5.23f);
        mPath.cubicTo(3.17f, 5.57f, 3.0f, 6.02f, 3.0f, 6.5f);
        mPath.lineTo(3.0f, 19.0f);
        mPath.rCubicTo(0.0f, 1.1f, 0.9f, 2.0f, 2.0f, 2.0f);
        mPath.rLineTo(14.0f, 0f);
        mPath.rCubicTo(1.1f, 0.0f, 2.0f, -0.9f, 2.0f, -2.0f);
        mPath.lineTo(21.0f, 6.5f);
        mPath.rCubicTo(0.0f, -0.48f, -0.17f, -0.93f, -0.46f, -1.27f);
        mPath.close();
        mPath.moveTo(20.54f, 5.23f);
        mPath.moveTo(12.0f, 17.5f);
        mPath.lineTo(6.5f, 12.0f);
        mPath.lineTo(10.0f, 12.0f);
        mPath.rLineTo(0f, -2.0f);
        mPath.rLineTo(4.0f, 0f);
        mPath.rLineTo(0f, 2.0f);
        mPath.rLineTo(3.5f, 0f);
        mPath.lineTo(12.0f, 17.5f);
        mPath.close();
        mPath.moveTo(12.0f, 17.5f);
        mPath.moveTo(5.12f, 5.0f);
        mPath.rLineTo(0.81f, -1.0f);
        mPath.rLineTo(12.0f, 0f);
        mPath.rLineTo(0.94f, 1.0f);
        mPath.lineTo(5.12f, 5.0f);
        mPath.close();
        mPath.moveTo(5.12f, 5.0f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        if (mFillPaint == null) {
            mFillPaint = new Paint();
            mFillPaint.setStyle(Paint.Style.FILL);
            mFillPaint.setAntiAlias(true);
        }
        mFillPaint.setColor(applyAlpha(-16777216, 1.0f));
        mFillPaint.setColorFilter(filter);
        canvas.drawPath(mRenderPath, mFillPaint);

    }

}