package com.github.megatronking.svg.iconlibs;

import android.content.Context;
import android.graphics.Canvas;
import android.graphics.ColorFilter;
import android.graphics.Paint;

import com.github.megatronking.svg.support.SVGRenderer;

/**
 * AUTO-GENERATED FILE.  DO NOT MODIFY.
 * 
 * This class was automatically generated by the
 * SVG-Generator. It should not be modified by hand.
 */
public class ic_backspace extends SVGRenderer {

    public ic_backspace(Context context) {
        super(context);
        mAlpha = 1.0f;
        mWidth = dip2px(24.0f);
        mHeight = dip2px(24.0f);
    }

    @Override
    public void render(Canvas canvas, int w, int h, ColorFilter filter) {
        final float scaleX = w / 24.0f;
        final float scaleY = h / 24.0f;
        
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(22.0f, 3.0f);
        mPath.lineTo(7.0f, 3.0f);
        mPath.rCubicTo(-0.69f, 0.0f, -1.23f, 0.35f, -1.59f, 0.88f);
        mPath.lineTo(0.0f, 12.0f);
        mPath.rLineTo(5.41f, 8.11f);
        mPath.rCubicTo(0.36f, 0.53f, 0.9f, 0.89f, 1.59f, 0.89f);
        mPath.rLineTo(15.0f, 0f);
        mPath.rCubicTo(1.1f, 0.0f, 2.0f, -0.9f, 2.0f, -2.0f);
        mPath.lineTo(24.0f, 5.0f);
        mPath.rCubicTo(0.0f, -1.1f, -0.9f, -2.0f, -2.0f, -2.0f);
        mPath.close();
        mPath.moveTo(22.0f, 3.0f);
        mPath.rMoveTo(-3.0f, 12.59f);
        mPath.lineTo(17.59f, 17.0f);
        mPath.lineTo(14.0f, 13.41f);
        mPath.lineTo(10.41f, 17.0f);
        mPath.lineTo(9.0f, 15.59f);
        mPath.lineTo(12.59f, 12.0f);
        mPath.lineTo(9.0f, 8.41f);
        mPath.lineTo(10.41f, 7.0f);
        mPath.lineTo(14.0f, 10.59f);
        mPath.lineTo(17.59f, 7.0f);
        mPath.lineTo(19.0f, 8.41f);
        mPath.lineTo(15.41f, 12.0f);
        mPath.lineTo(19.0f, 15.59f);
        mPath.close();
        mPath.moveTo(19.0f, 15.59f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        if (mFillPaint == null) {
            mFillPaint = new Paint();
            mFillPaint.setStyle(Paint.Style.FILL);
            mFillPaint.setAntiAlias(true);
        }
        mFillPaint.setColor(applyAlpha(-16777216, 1.0f));
        mFillPaint.setColorFilter(filter);
        canvas.drawPath(mRenderPath, mFillPaint);

    }

}