package com.github.megatronking.svg.iconlibs;

import android.content.Context;
import android.graphics.Canvas;
import android.graphics.ColorFilter;
import android.graphics.Paint;

import com.github.megatronking.svg.support.SVGRenderer;

/**
 * AUTO-GENERATED FILE.  DO NOT MODIFY.
 * 
 * This class was automatically generated by the
 * SVG-Generator. It should not be modified by hand.
 */
public class ic_content_cut extends SVGRenderer {

    public ic_content_cut(Context context) {
        super(context);
        mAlpha = 1.0f;
        mWidth = dip2px(24.0f);
        mHeight = dip2px(24.0f);
    }

    @Override
    public void render(Canvas canvas, int w, int h, ColorFilter filter) {
        final float scaleX = w / 24.0f;
        final float scaleY = h / 24.0f;
        
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(9.64f, 7.64f);
        mPath.rCubicTo(0.23f, -0.5f, 0.36f, -1.05f, 0.36f, -1.64f);
        mPath.rCubicTo(0.0f, -2.21f, -1.79f, -4.0f, -4.0f, -4.0f);
        mPath.cubicTo(3.79f, 2.0f, 2.0f, 3.79f, 2.0f, 6.0f);
        mPath.rCubicTo(0.0f, 2.21f, 1.79f, 4.0f, 4.0f, 4.0f);
        mPath.rCubicTo(0.59f, 0.0f, 1.14f, -0.13f, 1.64f, -0.36f);
        mPath.lineTo(10.0f, 12.0f);
        mPath.rLineTo(-2.36f, 2.36f);
        mPath.cubicTo(7.14f, 14.13f, 6.59f, 14.0f, 6.0f, 14.0f);
        mPath.rCubicTo(-2.21f, 0.0f, -4.0f, 1.79f, -4.0f, 4.0f);
        mPath.rCubicTo(0.0f, 2.21f, 1.79f, 4.0f, 4.0f, 4.0f);
        mPath.rCubicTo(2.21f, 0.0f, 4.0f, -1.79f, 4.0f, -4.0f);
        mPath.rCubicTo(0.0f, -0.59f, -0.13f, -1.14f, -0.36f, -1.64f);
        mPath.lineTo(12.0f, 14.0f);
        mPath.rLineTo(7.0f, 7.0f);
        mPath.rLineTo(3.0f, 0f);
        mPath.rLineTo(0f, -1.0f);
        mPath.lineTo(9.64f, 7.64f);
        mPath.close();
        mPath.moveTo(9.64f, 7.64f);
        mPath.moveTo(6.0f, 8.0f);
        mPath.rCubicTo(-1.1f, 0.0f, -2.0f, -0.89f, -2.0f, -2.0f);
        mPath.rCubicTo(0.0f, -1.1100001f, 0.9f, -2.0f, 2.0f, -2.0f);
        mPath.rCubicTo(1.0999999f, 0.0f, 2.0f, 0.89f, 2.0f, 2.0f);
        mPath.rCubicTo(0.0f, 1.1100001f, -0.9f, 2.0f, -2.0f, 2.0f);
        mPath.close();
        mPath.moveTo(6.0f, 8.0f);
        mPath.rMoveTo(0.0f, 12.0f);
        mPath.rCubicTo(-1.1f, 0.0f, -2.0f, -0.89f, -2.0f, -2.0f);
        mPath.rCubicTo(0.0f, -1.1100006f, 0.9f, -2.0f, 2.0f, -2.0f);
        mPath.rCubicTo(1.0999999f, 0.0f, 2.0f, 0.89f, 2.0f, 2.0f);
        mPath.rCubicTo(0.0f, 1.1100006f, -0.9f, 2.0f, -2.0f, 2.0f);
        mPath.close();
        mPath.moveTo(6.0f, 20.0f);
        mPath.rMoveTo(6.0f, -7.5f);
        mPath.rCubicTo(-0.28f, 0.0f, -0.5f, -0.22f, -0.5f, -0.5f);
        mPath.rCubicTo(0.0f, -0.27999973f, 0.22f, -0.5f, 0.5f, -0.5f);
        mPath.rCubicTo(0.27999973f, 0.0f, 0.5f, 0.22f, 0.5f, 0.5f);
        mPath.rCubicTo(0.0f, 0.27999973f, -0.22f, 0.5f, -0.5f, 0.5f);
        mPath.close();
        mPath.moveTo(12.0f, 12.5f);
        mPath.moveTo(19.0f, 3.0f);
        mPath.rLineTo(-6.0f, 6.0f);
        mPath.rLineTo(2.0f, 2.0f);
        mPath.rLineTo(7.0f, -7.0f);
        mPath.lineTo(22.0f, 3.0f);
        mPath.close();
        mPath.moveTo(19.0f, 3.0f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        if (mFillPaint == null) {
            mFillPaint = new Paint();
            mFillPaint.setStyle(Paint.Style.FILL);
            mFillPaint.setAntiAlias(true);
        }
        mFillPaint.setColor(applyAlpha(-16777216, 1.0f));
        mFillPaint.setColorFilter(filter);
        canvas.drawPath(mRenderPath, mFillPaint);

    }

}