package com.github.megatronking.svg.iconlibs;

import android.content.Context;
import android.graphics.Canvas;
import android.graphics.ColorFilter;
import android.graphics.Paint;

import com.github.megatronking.svg.support.SVGRenderer;

/**
 * AUTO-GENERATED FILE.  DO NOT MODIFY.
 * 
 * This class was automatically generated by the
 * SVG-Generator. It should not be modified by hand.
 */
public class ic_redo extends SVGRenderer {

    public ic_redo(Context context) {
        super(context);
        mAlpha = 1.0f;
        mWidth = dip2px(24.0f);
        mHeight = dip2px(24.0f);
    }

    @Override
    public void render(Canvas canvas, int w, int h, ColorFilter filter) {
        final float scaleX = w / 24.0f;
        final float scaleY = h / 24.0f;
        
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(18.4f, 10.6f);
        mPath.cubicTo(16.55f, 8.99f, 14.15f, 8.0f, 11.5f, 8.0f);
        mPath.rCubicTo(-4.65f, 0.0f, -8.58f, 3.03f, -9.96f, 7.22f);
        mPath.lineTo(3.9f, 16.0f);
        mPath.rCubicTo(1.05f, -3.19f, 4.05f, -5.5f, 7.6f, -5.5f);
        mPath.rCubicTo(1.95f, 0.0f, 3.73f, 0.72f, 5.12f, 1.88f);
        mPath.lineTo(13.0f, 16.0f);
        mPath.rLineTo(9.0f, 0f);
        mPath.lineTo(22.0f, 7.0f);
        mPath.rLineTo(-3.6f, 3.6f);
        mPath.close();
        mPath.moveTo(18.4f, 10.6f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        if (mFillPaint == null) {
            mFillPaint = new Paint();
            mFillPaint.setStyle(Paint.Style.FILL);
            mFillPaint.setAntiAlias(true);
        }
        mFillPaint.setColor(applyAlpha(-16777216, 1.0f));
        mFillPaint.setColorFilter(filter);
        canvas.drawPath(mRenderPath, mFillPaint);

    }

}