package com.github.megatronking.svg.iconlibs;

import android.content.Context;
import android.graphics.Canvas;
import android.graphics.ColorFilter;
import android.graphics.Paint;

import com.github.megatronking.svg.support.SVGRenderer;

/**
 * AUTO-GENERATED FILE.  DO NOT MODIFY.
 * 
 * This class was automatically generated by the
 * SVG-Generator. It should not be modified by hand.
 */
public class ic_text_format extends SVGRenderer {

    public ic_text_format(Context context) {
        super(context);
        mAlpha = 1.0f;
        mWidth = dip2px(24.0f);
        mHeight = dip2px(24.0f);
    }

    @Override
    public void render(Canvas canvas, int w, int h, ColorFilter filter) {
        final float scaleX = w / 24.0f;
        final float scaleY = h / 24.0f;
        
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(5.0f, 17.0f);
        mPath.rLineTo(0f, 2.0f);
        mPath.rLineTo(14.0f, 0f);
        mPath.rLineTo(0f, -2.0f);
        mPath.lineTo(5.0f, 17.0f);
        mPath.close();
        mPath.moveTo(5.0f, 17.0f);
        mPath.rMoveTo(4.5f, -4.2f);
        mPath.rLineTo(5.0f, 0f);
        mPath.rLineTo(0.9f, 2.2f);
        mPath.rLineTo(2.1f, 0f);
        mPath.lineTo(12.75f, 4.0f);
        mPath.rLineTo(-1.5f, 0f);
        mPath.lineTo(6.5f, 15.0f);
        mPath.rLineTo(2.1f, 0f);
        mPath.rLineTo(0.9f, -2.2f);
        mPath.close();
        mPath.moveTo(9.5f, 12.8f);
        mPath.moveTo(12.0f, 5.98f);
        mPath.lineTo(13.87f, 11.0f);
        mPath.rLineTo(-3.74f, 0f);
        mPath.lineTo(12.0f, 5.98f);
        mPath.close();
        mPath.moveTo(12.0f, 5.98f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        if (mFillPaint == null) {
            mFillPaint = new Paint();
            mFillPaint.setStyle(Paint.Style.FILL);
            mFillPaint.setAntiAlias(true);
        }
        mFillPaint.setColor(applyAlpha(-16777216, 1.0f));
        mFillPaint.setColorFilter(filter);
        canvas.drawPath(mRenderPath, mFillPaint);

    }

}