package com.github.megatronking.svg.iconlibs;

import android.content.Context;
import android.graphics.Canvas;
import android.graphics.ColorFilter;
import android.graphics.Paint;

import com.github.megatronking.svg.support.SVGRenderer;

/**
 * AUTO-GENERATED FILE.  DO NOT MODIFY.
 * 
 * This class was automatically generated by the
 * SVG-Generator. It should not be modified by hand.
 */
public class ic_add_shopping_cart extends SVGRenderer {

    public ic_add_shopping_cart(Context context) {
        super(context);
        mAlpha = 1.0f;
        mWidth = dip2px(24.0f);
        mHeight = dip2px(24.0f);
    }

    @Override
    public void render(Canvas canvas, int w, int h, ColorFilter filter) {
        final float scaleX = w / 24.0f;
        final float scaleY = h / 24.0f;
        
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(11.0f, 9.0f);
        mPath.rLineTo(2.0f, 0f);
        mPath.lineTo(13.0f, 6.0f);
        mPath.rLineTo(3.0f, 0f);
        mPath.lineTo(16.0f, 4.0f);
        mPath.rLineTo(-3.0f, 0f);
        mPath.lineTo(13.0f, 1.0f);
        mPath.rLineTo(-2.0f, 0f);
        mPath.rLineTo(0f, 3.0f);
        mPath.lineTo(8.0f, 4.0f);
        mPath.rLineTo(0f, 2.0f);
        mPath.rLineTo(3.0f, 0f);
        mPath.rLineTo(0f, 3.0f);
        mPath.close();
        mPath.moveTo(11.0f, 9.0f);
        mPath.rMoveTo(-4.0f, 9.0f);
        mPath.rCubicTo(-1.1f, 0.0f, -1.99f, 0.9f, -1.99f, 2.0f);
        mPath.cubicTo(5.01f, 21.1f, 5.9f, 22.0f, 7.0f, 22.0f);
        mPath.rCubicTo(1.0999999f, 0.0f, 2.0f, -0.9f, 2.0f, -2.0f);
        mPath.rCubicTo(0.0f, -1.1000004f, -0.9f, -2.0f, -2.0f, -2.0f);
        mPath.close();
        mPath.moveTo(7.0f, 18.0f);
        mPath.rMoveTo(10.0f, 0.0f);
        mPath.rCubicTo(-1.1f, 0.0f, -1.99f, 0.9f, -1.99f, 2.0f);
        mPath.rCubicTo(0.0f, 1.1000004f, 0.89f, 2.0f, 1.99f, 2.0f);
        mPath.rCubicTo(1.0999994f, 0.0f, 2.0f, -0.9f, 2.0f, -2.0f);
        mPath.rCubicTo(0.0f, -1.1000004f, -0.9f, -2.0f, -2.0f, -2.0f);
        mPath.close();
        mPath.moveTo(17.0f, 18.0f);
        mPath.rMoveTo(-9.83f, -3.25f);
        mPath.rLineTo(0.03f, -0.12f);
        mPath.rLineTo(0.9f, -1.63f);
        mPath.rLineTo(7.45f, 0f);
        mPath.rCubicTo(0.75f, 0.0f, 1.41f, -0.41f, 1.75f, -1.03f);
        mPath.rLineTo(3.86f, -7.01f);
        mPath.lineTo(19.42f, 4.0f);
        mPath.rLineTo(-0.01f, 0f);
        mPath.rLineTo(-1.1f, 2.0f);
        mPath.rLineTo(-2.76f, 5.0f);
        mPath.lineTo(8.53f, 11.0f);
        mPath.rLineTo(-0.13f, -0.27f);
        mPath.lineTo(6.16f, 6.0f);
        mPath.rLineTo(-0.95f, -2.0f);
        mPath.rLineTo(-0.94f, -2.0f);
        mPath.lineTo(1.0f, 2.0f);
        mPath.rLineTo(0f, 2.0f);
        mPath.rLineTo(2.0f, 0f);
        mPath.rLineTo(3.6f, 7.59f);
        mPath.rLineTo(-1.35f, 2.45f);
        mPath.rCubicTo(-0.16f, 0.28f, -0.25f, 0.61f, -0.25f, 0.96f);
        mPath.rCubicTo(0.0f, 1.1f, 0.9f, 2.0f, 2.0f, 2.0f);
        mPath.rLineTo(12.0f, 0f);
        mPath.rLineTo(0f, -2.0f);
        mPath.lineTo(7.42f, 15.0f);
        mPath.rCubicTo(-0.13f, 0.0f, -0.25f, -0.11f, -0.25f, -0.25f);
        mPath.close();
        mPath.moveTo(7.17f, 14.75f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        if (mFillPaint == null) {
            mFillPaint = new Paint();
            mFillPaint.setStyle(Paint.Style.FILL);
            mFillPaint.setAntiAlias(true);
        }
        mFillPaint.setColor(applyAlpha(-16777216, 1.0f));
        mFillPaint.setColorFilter(filter);
        canvas.drawPath(mRenderPath, mFillPaint);

    }

}