package com.github.megatronking.svg.iconlibs;

import android.content.Context;
import android.graphics.Canvas;
import android.graphics.ColorFilter;
import android.graphics.Paint;

import com.github.megatronking.svg.support.SVGRenderer;

/**
 * AUTO-GENERATED FILE.  DO NOT MODIFY.
 * 
 * This class was automatically generated by the
 * SVG-Generator. It should not be modified by hand.
 */
public class ic_build extends SVGRenderer {

    public ic_build(Context context) {
        super(context);
        mAlpha = 1.0f;
        mWidth = dip2px(24.0f);
        mHeight = dip2px(24.0f);
    }

    @Override
    public void render(Canvas canvas, int w, int h, ColorFilter filter) {
        final float scaleX = w / 24.0f;
        final float scaleY = h / 24.0f;
        
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(22.7f, 19.0f);
        mPath.rLineTo(-9.1f, -9.1f);
        mPath.rCubicTo(0.9f, -2.3f, 0.4f, -5.0f, -1.5f, -6.9f);
        mPath.rCubicTo(-2.0f, -2.0f, -5.0f, -2.4f, -7.4f, -1.3f);
        mPath.lineTo(9.0f, 6.0f);
        mPath.lineTo(6.0f, 9.0f);
        mPath.lineTo(1.6f, 4.7f);
        mPath.cubicTo(0.4f, 7.1f, 0.9f, 10.1f, 2.9f, 12.1f);
        mPath.rCubicTo(1.9f, 1.9f, 4.6f, 2.4f, 6.9f, 1.5f);
        mPath.rLineTo(9.1f, 9.1f);
        mPath.rCubicTo(0.4f, 0.4f, 1.0f, 0.4f, 1.4f, 0.0f);
        mPath.rLineTo(2.3f, -2.3f);
        mPath.rCubicTo(0.5f, -0.4f, 0.5f, -1.1f, 0.1f, -1.4f);
        mPath.close();
        mPath.moveTo(22.7f, 19.0f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        if (mFillPaint == null) {
            mFillPaint = new Paint();
            mFillPaint.setStyle(Paint.Style.FILL);
            mFillPaint.setAntiAlias(true);
        }
        mFillPaint.setColor(applyAlpha(-16777216, 1.0f));
        mFillPaint.setColorFilter(filter);
        canvas.drawPath(mRenderPath, mFillPaint);

    }

}