package com.github.megatronking.svg.iconlibs;

import android.content.Context;
import android.graphics.Canvas;
import android.graphics.ColorFilter;
import android.graphics.Paint;

import com.github.megatronking.svg.support.SVGRenderer;

/**
 * AUTO-GENERATED FILE.  DO NOT MODIFY.
 * 
 * This class was automatically generated by the
 * SVG-Generator. It should not be modified by hand.
 */
public class ic_fingerprint extends SVGRenderer {

    public ic_fingerprint(Context context) {
        super(context);
        mAlpha = 1.0f;
        mWidth = dip2px(24.0f);
        mHeight = dip2px(24.0f);
    }

    @Override
    public void render(Canvas canvas, int w, int h, ColorFilter filter) {
        final float scaleX = w / 24.0f;
        final float scaleY = h / 24.0f;
        
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(17.81f, 4.47f);
        mPath.rCubicTo(-0.08f, 0.0f, -0.16f, -0.02f, -0.23f, -0.06f);
        mPath.cubicTo(15.66f, 3.42f, 14.0f, 3.0f, 12.01f, 3.0f);
        mPath.rCubicTo(-1.98f, 0.0f, -3.86f, 0.47f, -5.57f, 1.41f);
        mPath.rCubicTo(-0.24f, 0.13f, -0.54f, 0.04f, -0.68f, -0.2f);
        mPath.rCubicTo(-0.13f, -0.24f, -0.04f, -0.55f, 0.2f, -0.68f);
        mPath.cubicTo(7.82f, 2.52f, 9.86f, 2.0f, 12.01f, 2.0f);
        mPath.rCubicTo(2.13f, 0.0f, 3.99f, 0.47f, 6.03f, 1.52f);
        mPath.rCubicTo(0.25f, 0.13f, 0.34f, 0.43f, 0.21f, 0.67f);
        mPath.rCubicTo(-0.09f, 0.18f, -0.26f, 0.28f, -0.44f, 0.28f);
        mPath.close();
        mPath.moveTo(17.81f, 4.47f);
        mPath.moveTo(3.5f, 9.72f);
        mPath.rCubicTo(-0.1f, 0.0f, -0.2f, -0.03f, -0.29f, -0.09f);
        mPath.rCubicTo(-0.23f, -0.16f, -0.28f, -0.47f, -0.12f, -0.7f);
        mPath.rCubicTo(0.99f, -1.4f, 2.25f, -2.5f, 3.75f, -3.27f);
        mPath.cubicTo(9.98f, 4.04f, 14.0f, 4.03f, 17.15f, 5.65f);
        mPath.rCubicTo(1.5f, 0.77f, 2.76f, 1.86f, 3.75f, 3.25f);
        mPath.rCubicTo(0.16f, 0.22f, 0.11f, 0.54f, -0.12f, 0.7f);
        mPath.rCubicTo(-0.23f, 0.16f, -0.54f, 0.11f, -0.7f, -0.12f);
        mPath.rCubicTo(-0.9f, -1.26f, -2.04f, -2.25f, -3.39f, -2.94f);
        mPath.rCubicTo(-2.87f, -1.47f, -6.54f, -1.47f, -9.4f, 0.01f);
        mPath.rCubicTo(-1.36f, 0.7f, -2.5f, 1.7f, -3.4f, 2.96f);
        mPath.rCubicTo(-0.08f, 0.14f, -0.23f, 0.21f, -0.39f, 0.21f);
        mPath.close();
        mPath.moveTo(3.5f, 9.72f);
        mPath.rMoveTo(6.25f, 12.07f);
        mPath.rCubicTo(-0.13f, 0.0f, -0.26f, -0.05f, -0.35f, -0.15f);
        mPath.rCubicTo(-0.87f, -0.87f, -1.34f, -1.43f, -2.01f, -2.64f);
        mPath.rCubicTo(-0.69f, -1.23f, -1.05f, -2.73f, -1.05f, -4.34f);
        mPath.rCubicTo(0.0f, -2.97f, 2.54f, -5.39f, 5.66f, -5.39f);
        mPath.rCubicTo(3.12f, 0.0f, 5.66f, 2.42f, 5.66f, 5.39f);
        mPath.rCubicTo(0.0f, 0.28f, -0.22f, 0.5f, -0.5f, 0.5f);
        mPath.rCubicTo(-0.2800007f, 0.0f, -0.5f, -0.22f, -0.5f, -0.5f);
        mPath.rCubicTo(0.0f, -2.42f, -2.09f, -4.39f, -4.66f, -4.39f);
        mPath.rCubicTo(-2.57f, 0.0f, -4.66f, 1.97f, -4.66f, 4.39f);
        mPath.rCubicTo(0.0f, 1.44f, 0.32f, 2.77f, 0.93f, 3.85f);
        mPath.rCubicTo(0.64f, 1.15f, 1.08f, 1.64f, 1.85f, 2.42f);
        mPath.rCubicTo(0.19f, 0.2f, 0.19f, 0.51f, 0.0f, 0.71f);
        mPath.rCubicTo(-0.11f, 0.1f, -0.24f, 0.15f, -0.37f, 0.15f);
        mPath.close();
        mPath.moveTo(9.75f, 21.79f);
        mPath.rMoveTo(7.17f, -1.85f);
        mPath.rCubicTo(-1.19f, 0.0f, -2.24f, -0.3f, -3.1f, -0.89f);
        mPath.rCubicTo(-1.49f, -1.01f, -2.38f, -2.65f, -2.38f, -4.39f);
        mPath.rCubicTo(0.0f, -0.28f, 0.22f, -0.5f, 0.5f, -0.5f);
        mPath.rCubicTo(0.27999973f, 0.0f, 0.5f, 0.22f, 0.5f, 0.5f);
        mPath.rCubicTo(0.0f, 1.41f, 0.72f, 2.74f, 1.94f, 3.56f);
        mPath.rCubicTo(0.71f, 0.48f, 1.54f, 0.71f, 2.54f, 0.71f);
        mPath.rCubicTo(0.24f, 0.0f, 0.64f, -0.03f, 1.04f, -0.1f);
        mPath.rCubicTo(0.27f, -0.05f, 0.53f, 0.13f, 0.58f, 0.41f);
        mPath.rCubicTo(0.05f, 0.27f, -0.13f, 0.53f, -0.41f, 0.58f);
        mPath.rCubicTo(-0.57f, 0.11f, -1.07f, 0.12f, -1.21f, 0.12f);
        mPath.close();
        mPath.moveTo(16.92f, 19.94f);
        mPath.moveTo(14.91f, 22.0f);
        mPath.rCubicTo(-0.04f, 0.0f, -0.09f, -0.01f, -0.13f, -0.02f);
        mPath.rCubicTo(-1.59f, -0.44f, -2.63f, -1.03f, -3.72f, -2.1f);
        mPath.rCubicTo(-1.4f, -1.39f, -2.17f, -3.24f, -2.17f, -5.22f);
        mPath.rCubicTo(0.0f, -1.62f, 1.38f, -2.94f, 3.08f, -2.94f);
        mPath.rCubicTo(1.7f, 0.0f, 3.08f, 1.32f, 3.08f, 2.94f);
        mPath.rCubicTo(0.0f, 1.07f, 0.93f, 1.94f, 2.08f, 1.94f);
        mPath.rCubicTo(1.1499996f, 0.0f, 2.08f, -0.87f, 2.08f, -1.94f);
        mPath.rCubicTo(0.0f, -3.77f, -3.25f, -6.83f, -7.25f, -6.83f);
        mPath.rCubicTo(-2.84f, 0.0f, -5.44f, 1.58f, -6.61f, 4.03f);
        mPath.rCubicTo(-0.39f, 0.81f, -0.59f, 1.76f, -0.59f, 2.8f);
        mPath.rCubicTo(0.0f, 0.78f, 0.07f, 2.01f, 0.67f, 3.61f);
        mPath.rCubicTo(0.1f, 0.26f, -0.03f, 0.55f, -0.29f, 0.64f);
        mPath.rCubicTo(-0.26f, 0.1f, -0.55f, -0.04f, -0.64f, -0.29f);
        mPath.rCubicTo(-0.49f, -1.31f, -0.73f, -2.61f, -0.73f, -3.96f);
        mPath.rCubicTo(0.0f, -1.2f, 0.23f, -2.29f, 0.68f, -3.24f);
        mPath.rCubicTo(1.33f, -2.79f, 4.28f, -4.6f, 7.51f, -4.6f);
        mPath.rCubicTo(4.55f, 0.0f, 8.25f, 3.51f, 8.25f, 7.83f);
        mPath.rCubicTo(0.0f, 1.62f, -1.38f, 2.94f, -3.08f, 2.94f);
        mPath.rCubicTo(-1.7000008f, 0.0f, -3.08f, -1.32f, -3.08f, -2.94f);
        mPath.rCubicTo(0.0f, -1.07f, -0.93f, -1.94f, -2.08f, -1.94f);
        mPath.rCubicTo(-1.1499996f, 0.0f, -2.08f, 0.87f, -2.08f, 1.94f);
        mPath.rCubicTo(0.0f, 1.71f, 0.66f, 3.31f, 1.87f, 4.51f);
        mPath.rCubicTo(0.95f, 0.94f, 1.86f, 1.46f, 3.27f, 1.85f);
        mPath.rCubicTo(0.27f, 0.07f, 0.42f, 0.35f, 0.35f, 0.61f);
        mPath.rCubicTo(-0.05f, 0.23f, -0.26f, 0.38f, -0.47f, 0.38f);
        mPath.close();
        mPath.moveTo(14.91f, 22.0f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        if (mFillPaint == null) {
            mFillPaint = new Paint();
            mFillPaint.setStyle(Paint.Style.FILL);
            mFillPaint.setAntiAlias(true);
        }
        mFillPaint.setColor(applyAlpha(-16777216, 1.0f));
        mFillPaint.setColorFilter(filter);
        canvas.drawPath(mRenderPath, mFillPaint);

    }

}