package com.github.megatronking.svg.iconlibs;

import android.content.Context;
import android.graphics.Canvas;
import android.graphics.ColorFilter;
import android.graphics.Paint;

import com.github.megatronking.svg.support.SVGRenderer;

/**
 * AUTO-GENERATED FILE.  DO NOT MODIFY.
 * 
 * This class was automatically generated by the
 * SVG-Generator. It should not be modified by hand.
 */
public class ic_record_voice_over extends SVGRenderer {

    public ic_record_voice_over(Context context) {
        super(context);
        mAlpha = 1.0f;
        mWidth = dip2px(24.0f);
        mHeight = dip2px(24.0f);
    }

    @Override
    public void render(Canvas canvas, int w, int h, ColorFilter filter) {
        final float scaleX = w / 24.0f;
        final float scaleY = h / 24.0f;
        
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(9.0f, 9.0f);
        mPath.rMoveTo(-4.0f, 0.0f);
        mPath.cubicTo(5.0f, 7.939541f, 5.4217153f, 6.9214306f, 6.1715727f, 6.1715727f);
        mPath.cubicTo(6.9214306f, 5.4217153f, 7.939541f, 5.0f, 9.0f, 5.0f);
        mPath.cubicTo(10.060459f, 5.0f, 11.078569f, 5.4217153f, 11.828427f, 6.1715727f);
        mPath.cubicTo(12.578285f, 6.9214306f, 13.0f, 7.939541f, 13.0f, 9.0f);
        mPath.cubicTo(13.0f, 10.060459f, 12.578285f, 11.078569f, 11.828427f, 11.828427f);
        mPath.cubicTo(11.078569f, 12.578285f, 10.060459f, 13.0f, 9.0f, 13.0f);
        mPath.cubicTo(7.939541f, 13.0f, 6.9214306f, 12.578285f, 6.1715727f, 11.828427f);
        mPath.cubicTo(5.4217153f, 11.078569f, 5.0f, 10.060459f, 5.0f, 9.0f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        if (mFillPaint == null) {
            mFillPaint = new Paint();
            mFillPaint.setStyle(Paint.Style.FILL);
            mFillPaint.setAntiAlias(true);
        }
        mFillPaint.setColor(applyAlpha(-16777216, 1.0f));
        mFillPaint.setColorFilter(filter);
        canvas.drawPath(mRenderPath, mFillPaint);
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(9.0f, 15.0f);
        mPath.rCubicTo(-2.67f, 0.0f, -8.0f, 1.34f, -8.0f, 4.0f);
        mPath.rLineTo(0f, 2.0f);
        mPath.rLineTo(16.0f, 0f);
        mPath.rLineTo(0f, -2.0f);
        mPath.rCubicTo(0.0f, -2.66f, -5.33f, -4.0f, -8.0f, -4.0f);
        mPath.close();
        mPath.moveTo(9.0f, 15.0f);
        mPath.rMoveTo(7.76f, -9.64f);
        mPath.rLineTo(-1.68f, 1.69f);
        mPath.rCubicTo(0.84f, 1.18f, 0.84f, 2.71f, 0.0f, 3.89f);
        mPath.rLineTo(1.68f, 1.69f);
        mPath.rCubicTo(2.02f, -2.02f, 2.02f, -5.07f, 0.0f, -7.27f);
        mPath.close();
        mPath.moveTo(16.76f, 5.3599997f);
        mPath.moveTo(20.07f, 2.0f);
        mPath.rLineTo(-1.63f, 1.63f);
        mPath.rCubicTo(2.77f, 3.02f, 2.77f, 7.56f, 0.0f, 10.74f);
        mPath.lineTo(20.07f, 16.0f);
        mPath.rCubicTo(3.9f, -3.89f, 3.91f, -9.95f, 0.0f, -14.0f);
        mPath.close();
        mPath.moveTo(20.07f, 2.0f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        mFillPaint.setColor(applyAlpha(-16777216, 1.0f));
        mFillPaint.setColorFilter(filter);
        canvas.drawPath(mRenderPath, mFillPaint);

    }

}