package com.github.megatronking.svg.iconlibs;

import android.content.Context;
import android.graphics.Canvas;
import android.graphics.ColorFilter;
import android.graphics.Paint;

import com.github.megatronking.svg.support.SVGRenderer;

/**
 * AUTO-GENERATED FILE.  DO NOT MODIFY.
 * 
 * This class was automatically generated by the
 * SVG-Generator. It should not be modified by hand.
 */
public class ic_restore_page extends SVGRenderer {

    public ic_restore_page(Context context) {
        super(context);
        mAlpha = 1.0f;
        mWidth = dip2px(24.0f);
        mHeight = dip2px(24.0f);
    }

    @Override
    public void render(Canvas canvas, int w, int h, ColorFilter filter) {
        final float scaleX = w / 24.0f;
        final float scaleY = h / 24.0f;
        
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(14.0f, 2.0f);
        mPath.lineTo(6.0f, 2.0f);
        mPath.rCubicTo(-1.1f, 0.0f, -1.99f, 0.9f, -1.99f, 2.0f);
        mPath.lineTo(4.0f, 20.0f);
        mPath.rCubicTo(0.0f, 1.1f, 0.89f, 2.0f, 1.99f, 2.0f);
        mPath.lineTo(18.0f, 22.0f);
        mPath.rCubicTo(1.1f, 0.0f, 2.0f, -0.9f, 2.0f, -2.0f);
        mPath.lineTo(20.0f, 8.0f);
        mPath.rLineTo(-6.0f, -6.0f);
        mPath.close();
        mPath.moveTo(14.0f, 2.0f);
        mPath.rMoveTo(-2.0f, 16.0f);
        mPath.rCubicTo(-2.05f, 0.0f, -3.81f, -1.24f, -4.58f, -3.0f);
        mPath.rLineTo(1.71f, 0f);
        mPath.rCubicTo(0.63f, 0.9f, 1.68f, 1.5f, 2.87f, 1.5f);
        mPath.rCubicTo(1.93f, 0.0f, 3.5f, -1.57f, 3.5f, -3.5f);
        mPath.cubicTo(15.5f, 11.07f, 13.93f, 9.5f, 12.0f, 9.5f);
        mPath.rCubicTo(-1.35f, 0.0f, -2.52f, 0.78f, -3.1f, 1.9f);
        mPath.rLineTo(1.6f, 1.6f);
        mPath.rLineTo(-4.0f, 0f);
        mPath.lineTo(6.5f, 9.0f);
        mPath.rLineTo(1.3f, 1.3f);
        mPath.cubicTo(8.69f, 8.92f, 10.23f, 8.0f, 12.0f, 8.0f);
        mPath.rCubicTo(2.76f, 0.0f, 5.0f, 2.24f, 5.0f, 5.0f);
        mPath.rCubicTo(0.0f, 2.7600002f, -2.24f, 5.0f, -5.0f, 5.0f);
        mPath.close();
        mPath.moveTo(12.0f, 18.0f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        if (mFillPaint == null) {
            mFillPaint = new Paint();
            mFillPaint.setStyle(Paint.Style.FILL);
            mFillPaint.setAntiAlias(true);
        }
        mFillPaint.setColor(applyAlpha(-16777216, 1.0f));
        mFillPaint.setColorFilter(filter);
        canvas.drawPath(mRenderPath, mFillPaint);

    }

}