package com.github.megatronking.svg.iconlibs;

import android.content.Context;
import android.graphics.Canvas;
import android.graphics.ColorFilter;
import android.graphics.Paint;

import com.github.megatronking.svg.support.SVGRenderer;

/**
 * AUTO-GENERATED FILE.  DO NOT MODIFY.
 * 
 * This class was automatically generated by the
 * SVG-Generator. It should not be modified by hand.
 */
public class ic_settings_ethernet extends SVGRenderer {

    public ic_settings_ethernet(Context context) {
        super(context);
        mAlpha = 1.0f;
        mWidth = dip2px(24.0f);
        mHeight = dip2px(24.0f);
    }

    @Override
    public void render(Canvas canvas, int w, int h, ColorFilter filter) {
        final float scaleX = w / 24.0f;
        final float scaleY = h / 24.0f;
        
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(7.77f, 6.76f);
        mPath.lineTo(6.23f, 5.48f);
        mPath.lineTo(0.82f, 12.0f);
        mPath.rLineTo(5.41f, 6.52f);
        mPath.rLineTo(1.54f, -1.28f);
        mPath.lineTo(3.42f, 12.0f);
        mPath.rLineTo(4.35f, -5.24f);
        mPath.close();
        mPath.moveTo(7.77f, 6.76f);
        mPath.moveTo(7.0f, 13.0f);
        mPath.rLineTo(2.0f, 0f);
        mPath.rLineTo(0f, -2.0f);
        mPath.lineTo(7.0f, 11.0f);
        mPath.rLineTo(0f, 2.0f);
        mPath.close();
        mPath.moveTo(7.0f, 13.0f);
        mPath.rMoveTo(10.0f, -2.0f);
        mPath.rLineTo(-2.0f, 0f);
        mPath.rLineTo(0f, 2.0f);
        mPath.rLineTo(2.0f, 0f);
        mPath.rLineTo(0f, -2.0f);
        mPath.close();
        mPath.moveTo(17.0f, 11.0f);
        mPath.rMoveTo(-6.0f, 2.0f);
        mPath.rLineTo(2.0f, 0f);
        mPath.rLineTo(0f, -2.0f);
        mPath.rLineTo(-2.0f, 0f);
        mPath.rLineTo(0f, 2.0f);
        mPath.close();
        mPath.moveTo(11.0f, 13.0f);
        mPath.rMoveTo(6.77f, -7.52f);
        mPath.rLineTo(-1.54f, 1.28f);
        mPath.lineTo(20.58f, 12.0f);
        mPath.rLineTo(-4.35f, 5.24f);
        mPath.rLineTo(1.54f, 1.28f);
        mPath.lineTo(23.18f, 12.0f);
        mPath.rLineTo(-5.41f, -6.52f);
        mPath.close();
        mPath.moveTo(17.77f, 5.48f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        if (mFillPaint == null) {
            mFillPaint = new Paint();
            mFillPaint.setStyle(Paint.Style.FILL);
            mFillPaint.setAntiAlias(true);
        }
        mFillPaint.setColor(applyAlpha(-16777216, 1.0f));
        mFillPaint.setColorFilter(filter);
        canvas.drawPath(mRenderPath, mFillPaint);

    }

}