package com.github.megatronking.svg.iconlibs;

import android.content.Context;
import android.graphics.Canvas;
import android.graphics.ColorFilter;
import android.graphics.Paint;

import com.github.megatronking.svg.support.SVGRenderer;

/**
 * AUTO-GENERATED FILE.  DO NOT MODIFY.
 * 
 * This class was automatically generated by the
 * SVG-Generator. It should not be modified by hand.
 */
public class ic_supervisor_account extends SVGRenderer {

    public ic_supervisor_account(Context context) {
        super(context);
        mAlpha = 1.0f;
        mWidth = dip2px(24.0f);
        mHeight = dip2px(24.0f);
    }

    @Override
    public void render(Canvas canvas, int w, int h, ColorFilter filter) {
        final float scaleX = w / 24.0f;
        final float scaleY = h / 24.0f;
        
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(16.5f, 12.0f);
        mPath.rCubicTo(1.38f, 0.0f, 2.49f, -1.12f, 2.49f, -2.5f);
        mPath.cubicTo(18.99f, 8.12f, 17.88f, 7.0f, 16.5f, 7.0f);
        mPath.cubicTo(15.12f, 7.0f, 14.0f, 8.12f, 14.0f, 9.5f);
        mPath.rCubicTo(0.0f, 1.3800001f, 1.12f, 2.5f, 2.5f, 2.5f);
        mPath.close();
        mPath.moveTo(16.5f, 12.0f);
        mPath.moveTo(9.0f, 11.0f);
        mPath.rCubicTo(1.66f, 0.0f, 2.99f, -1.34f, 2.99f, -3.0f);
        mPath.cubicTo(11.99f, 6.34f, 10.66f, 5.0f, 9.0f, 5.0f);
        mPath.cubicTo(7.34f, 5.0f, 6.0f, 6.34f, 6.0f, 8.0f);
        mPath.rCubicTo(0.0f, 1.6599998f, 1.34f, 3.0f, 3.0f, 3.0f);
        mPath.close();
        mPath.moveTo(9.0f, 11.0f);
        mPath.rMoveTo(7.5f, 3.0f);
        mPath.rCubicTo(-1.83f, 0.0f, -5.5f, 0.92f, -5.5f, 2.75f);
        mPath.lineTo(11.0f, 19.0f);
        mPath.rLineTo(11.0f, 0f);
        mPath.rLineTo(0f, -2.25f);
        mPath.rCubicTo(0.0f, -1.83f, -3.67f, -2.75f, -5.5f, -2.75f);
        mPath.close();
        mPath.moveTo(16.5f, 14.0f);
        mPath.moveTo(9.0f, 13.0f);
        mPath.rCubicTo(-2.33f, 0.0f, -7.0f, 1.17f, -7.0f, 3.5f);
        mPath.lineTo(2.0f, 19.0f);
        mPath.rLineTo(7.0f, 0f);
        mPath.rLineTo(0f, -2.25f);
        mPath.rCubicTo(0.0f, -0.85f, 0.33f, -2.34f, 2.37f, -3.47f);
        mPath.cubicTo(10.5f, 13.1f, 9.66f, 13.0f, 9.0f, 13.0f);
        mPath.close();
        mPath.moveTo(9.0f, 13.0f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        if (mFillPaint == null) {
            mFillPaint = new Paint();
            mFillPaint.setStyle(Paint.Style.FILL);
            mFillPaint.setAntiAlias(true);
        }
        mFillPaint.setColor(applyAlpha(-16777216, 1.0f));
        mFillPaint.setColorFilter(filter);
        canvas.drawPath(mRenderPath, mFillPaint);

    }

}