package com.github.megatronking.svg.iconlibs;

import android.content.Context;
import android.graphics.Canvas;
import android.graphics.ColorFilter;
import android.graphics.Paint;

import com.github.megatronking.svg.support.SVGRenderer;

/**
 * AUTO-GENERATED FILE.  DO NOT MODIFY.
 * 
 * This class was automatically generated by the
 * SVG-Generator. It should not be modified by hand.
 */
public class ic_track_changes extends SVGRenderer {

    public ic_track_changes(Context context) {
        super(context);
        mAlpha = 1.0f;
        mWidth = dip2px(24.0f);
        mHeight = dip2px(24.0f);
    }

    @Override
    public void render(Canvas canvas, int w, int h, ColorFilter filter) {
        final float scaleX = w / 24.0f;
        final float scaleY = h / 24.0f;
        
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(19.07f, 4.93f);
        mPath.rLineTo(-1.41f, 1.41f);
        mPath.cubicTo(19.1f, 7.79f, 20.0f, 9.79f, 20.0f, 12.0f);
        mPath.rCubicTo(0.0f, 4.42f, -3.58f, 8.0f, -8.0f, 8.0f);
        mPath.rCubicTo(-4.42f, 0.0f, -8.0f, -3.58f, -8.0f, -8.0f);
        mPath.rCubicTo(0.0f, -4.08f, 3.05f, -7.44f, 7.0f, -7.93f);
        mPath.rLineTo(0f, 2.02f);
        mPath.cubicTo(8.16f, 6.57f, 6.0f, 9.03f, 6.0f, 12.0f);
        mPath.rCubicTo(0.0f, 3.31f, 2.69f, 6.0f, 6.0f, 6.0f);
        mPath.rCubicTo(3.3099995f, 0.0f, 6.0f, -2.69f, 6.0f, -6.0f);
        mPath.rCubicTo(0.0f, -1.66f, -0.67f, -3.16f, -1.76f, -4.24f);
        mPath.rLineTo(-1.41f, 1.41f);
        mPath.cubicTo(15.55f, 9.9f, 16.0f, 10.9f, 16.0f, 12.0f);
        mPath.rCubicTo(0.0f, 2.21f, -1.79f, 4.0f, -4.0f, 4.0f);
        mPath.rCubicTo(-2.21f, 0.0f, -4.0f, -1.79f, -4.0f, -4.0f);
        mPath.rCubicTo(0.0f, -1.86f, 1.28f, -3.41f, 3.0f, -3.86f);
        mPath.rLineTo(0f, 2.14f);
        mPath.rCubicTo(-0.6f, 0.35f, -1.0f, 0.98f, -1.0f, 1.72f);
        mPath.rCubicTo(0.0f, 1.1f, 0.9f, 2.0f, 2.0f, 2.0f);
        mPath.rCubicTo(1.1000004f, 0.0f, 2.0f, -0.9f, 2.0f, -2.0f);
        mPath.rCubicTo(0.0f, -0.74f, -0.4f, -1.38f, -1.0f, -1.72f);
        mPath.lineTo(13.0f, 2.0f);
        mPath.rLineTo(-1.0f, 0f);
        mPath.cubicTo(6.48f, 2.0f, 2.0f, 6.48f, 2.0f, 12.0f);
        mPath.rCubicTo(0.0f, 5.52f, 4.48f, 10.0f, 10.0f, 10.0f);
        mPath.rCubicTo(5.52f, 0.0f, 10.0f, -4.48f, 10.0f, -10.0f);
        mPath.rCubicTo(0.0f, -2.76f, -1.12f, -5.26f, -2.93f, -7.07f);
        mPath.close();
        mPath.moveTo(19.07f, 4.93f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        if (mFillPaint == null) {
            mFillPaint = new Paint();
            mFillPaint.setStyle(Paint.Style.FILL);
            mFillPaint.setAntiAlias(true);
        }
        mFillPaint.setColor(applyAlpha(-16777216, 1.0f));
        mFillPaint.setColorFilter(filter);
        canvas.drawPath(mRenderPath, mFillPaint);

    }

}