package com.github.megatronking.svg.iconlibs;

import android.content.Context;
import android.graphics.Canvas;
import android.graphics.ColorFilter;
import android.graphics.Paint;

import com.github.megatronking.svg.support.SVGRenderer;

/**
 * AUTO-GENERATED FILE.  DO NOT MODIFY.
 * 
 * This class was automatically generated by the
 * SVG-Generator. It should not be modified by hand.
 */
public class ic_youtube_searched_for extends SVGRenderer {

    public ic_youtube_searched_for(Context context) {
        super(context);
        mAlpha = 1.0f;
        mWidth = dip2px(24.0f);
        mHeight = dip2px(24.0f);
    }

    @Override
    public void render(Canvas canvas, int w, int h, ColorFilter filter) {
        final float scaleX = w / 24.0f;
        final float scaleY = h / 24.0f;
        
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(17.01f, 14.0f);
        mPath.rLineTo(-0.8f, 0f);
        mPath.rLineTo(-0.27f, -0.27f);
        mPath.rCubicTo(0.98f, -1.14f, 1.57f, -2.61f, 1.57f, -4.23f);
        mPath.rCubicTo(0.0f, -3.59f, -2.91f, -6.5f, -6.5f, -6.5f);
        mPath.rCubicTo(-3.5900002f, 0.0f, -6.5f, 3.0f, -6.5f, 6.5f);
        mPath.lineTo(2.0f, 9.5f);
        mPath.rLineTo(3.84f, 4.0f);
        mPath.rLineTo(4.16f, -4.0f);
        mPath.lineTo(6.51f, 9.5f);
        mPath.cubicTo(6.51f, 7.0f, 8.53f, 5.0f, 11.01f, 5.0f);
        mPath.rCubicTo(2.4800005f, 0.0f, 4.5f, 2.01f, 4.5f, 4.5f);
        mPath.rCubicTo(0.0f, 2.48f, -2.02f, 4.5f, -4.5f, 4.5f);
        mPath.rCubicTo(-0.65f, 0.0f, -1.26f, -0.14f, -1.82f, -0.38f);
        mPath.lineTo(7.71f, 15.1f);
        mPath.rCubicTo(0.97f, 0.57f, 2.09f, 0.9f, 3.3f, 0.9f);
        mPath.rCubicTo(1.61f, 0.0f, 3.08f, -0.59f, 4.22f, -1.57f);
        mPath.rLineTo(0.27f, 0.27f);
        mPath.rLineTo(0f, 0.79f);
        mPath.rLineTo(5.01f, 4.99f);
        mPath.lineTo(22.0f, 19.0f);
        mPath.rLineTo(-4.99f, -5.0f);
        mPath.close();
        mPath.moveTo(17.01f, 14.0f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        if (mFillPaint == null) {
            mFillPaint = new Paint();
            mFillPaint.setStyle(Paint.Style.FILL);
            mFillPaint.setAntiAlias(true);
        }
        mFillPaint.setColor(applyAlpha(-16777216, 1.0f));
        mFillPaint.setColorFilter(filter);
        canvas.drawPath(mRenderPath, mFillPaint);

    }

}