package com.github.megatronking.svg.iconlibs;

import android.content.Context;
import android.graphics.Canvas;
import android.graphics.ColorFilter;
import android.graphics.Paint;

import com.github.megatronking.svg.support.SVGRenderer;

/**
 * AUTO-GENERATED FILE.  DO NOT MODIFY.
 * 
 * This class was automatically generated by the
 * SVG-Generator. It should not be modified by hand.
 */
public class ic_beenhere extends SVGRenderer {

    public ic_beenhere(Context context) {
        super(context);
        mAlpha = 1.0f;
        mWidth = dip2px(24.0f);
        mHeight = dip2px(24.0f);
    }

    @Override
    public void render(Canvas canvas, int w, int h, ColorFilter filter) {
        final float scaleX = w / 24.0f;
        final float scaleY = h / 24.0f;
        
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(19.0f, 1.0f);
        mPath.lineTo(5.0f, 1.0f);
        mPath.rCubicTo(-1.1f, 0.0f, -1.99f, 0.9f, -1.99f, 2.0f);
        mPath.lineTo(3.0f, 15.93f);
        mPath.rCubicTo(0.0f, 0.69f, 0.35f, 1.3f, 0.88f, 1.66f);
        mPath.lineTo(12.0f, 23.0f);
        mPath.rLineTo(8.11f, -5.41f);
        mPath.rCubicTo(0.53f, -0.36f, 0.88f, -0.97f, 0.88f, -1.66f);
        mPath.lineTo(21.0f, 3.0f);
        mPath.rCubicTo(0.0f, -1.1f, -0.9f, -2.0f, -2.0f, -2.0f);
        mPath.close();
        mPath.moveTo(19.0f, 1.0f);
        mPath.rMoveTo(-9.0f, 15.0f);
        mPath.rLineTo(-5.0f, -5.0f);
        mPath.rLineTo(1.41f, -1.41f);
        mPath.lineTo(10.0f, 13.17f);
        mPath.rLineTo(7.59f, -7.59f);
        mPath.lineTo(19.0f, 7.0f);
        mPath.rLineTo(-9.0f, 9.0f);
        mPath.close();
        mPath.moveTo(10.0f, 16.0f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        if (mFillPaint == null) {
            mFillPaint = new Paint();
            mFillPaint.setStyle(Paint.Style.FILL);
            mFillPaint.setAntiAlias(true);
        }
        mFillPaint.setColor(applyAlpha(-16777216, 1.0f));
        mFillPaint.setColorFilter(filter);
        canvas.drawPath(mRenderPath, mFillPaint);

    }

}