package com.github.megatronking.svg.iconlibs;

import android.content.Context;
import android.graphics.Canvas;
import android.graphics.ColorFilter;
import android.graphics.Paint;

import com.github.megatronking.svg.support.SVGRenderer;

/**
 * AUTO-GENERATED FILE.  DO NOT MODIFY.
 * 
 * This class was automatically generated by the
 * SVG-Generator. It should not be modified by hand.
 */
public class ic_directions_bike extends SVGRenderer {

    public ic_directions_bike(Context context) {
        super(context);
        mAlpha = 1.0f;
        mWidth = dip2px(24.0f);
        mHeight = dip2px(24.0f);
    }

    @Override
    public void render(Canvas canvas, int w, int h, ColorFilter filter) {
        final float scaleX = w / 24.0f;
        final float scaleY = h / 24.0f;
        
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(15.5f, 5.5f);
        mPath.rCubicTo(1.1f, 0.0f, 2.0f, -0.9f, 2.0f, -2.0f);
        mPath.rCubicTo(0.0f, -1.0999999f, -0.9f, -2.0f, -2.0f, -2.0f);
        mPath.rCubicTo(-1.1000004f, 0.0f, -2.0f, 0.9f, -2.0f, 2.0f);
        mPath.rCubicTo(0.0f, 1.0999999f, 0.9f, 2.0f, 2.0f, 2.0f);
        mPath.close();
        mPath.moveTo(15.5f, 5.5f);
        mPath.moveTo(5.0f, 12.0f);
        mPath.rCubicTo(-2.8f, 0.0f, -5.0f, 2.2f, -5.0f, 5.0f);
        mPath.rCubicTo(0.0f, 2.8000002f, 2.2f, 5.0f, 5.0f, 5.0f);
        mPath.rCubicTo(2.8f, 0.0f, 5.0f, -2.2f, 5.0f, -5.0f);
        mPath.rCubicTo(0.0f, -2.7999992f, -2.2f, -5.0f, -5.0f, -5.0f);
        mPath.close();
        mPath.moveTo(5.0f, 12.0f);
        mPath.rMoveTo(0.0f, 8.5f);
        mPath.rCubicTo(-1.9f, 0.0f, -3.5f, -1.6f, -3.5f, -3.5f);
        mPath.rCubicTo(0.0f, -1.8999996f, 1.6f, -3.5f, 3.5f, -3.5f);
        mPath.rCubicTo(1.9000001f, 0.0f, 3.5f, 1.6f, 3.5f, 3.5f);
        mPath.rCubicTo(0.0f, 1.8999996f, -1.6f, 3.5f, -3.5f, 3.5f);
        mPath.close();
        mPath.moveTo(5.0f, 20.5f);
        mPath.rMoveTo(5.8f, -10.0f);
        mPath.rLineTo(2.4f, -2.4f);
        mPath.rLineTo(0.8f, 0.8f);
        mPath.rCubicTo(1.3f, 1.3f, 3.0f, 2.1f, 5.1f, 2.1f);
        mPath.lineTo(19.1f, 9.0f);
        mPath.rCubicTo(-1.5f, 0.0f, -2.7f, -0.6f, -3.6f, -1.5f);
        mPath.rLineTo(-1.9f, -1.9f);
        mPath.rCubicTo(-0.5f, -0.4f, -1.0f, -0.6f, -1.6f, -0.6f);
        mPath.rCubicTo(-0.6000004f, 0.0f, -1.1f, 0.2f, -1.4f, 0.6f);
        mPath.lineTo(7.8f, 8.4f);
        mPath.rCubicTo(-0.4f, 0.4f, -0.6f, 0.9f, -0.6f, 1.4f);
        mPath.rCubicTo(0.0f, 0.6f, 0.2f, 1.1f, 0.6f, 1.4f);
        mPath.lineTo(11.0f, 14.0f);
        mPath.rLineTo(0f, 5.0f);
        mPath.rLineTo(2.0f, 0f);
        mPath.rLineTo(0f, -6.2f);
        mPath.rLineTo(-2.2f, -2.3f);
        mPath.close();
        mPath.moveTo(10.8f, 10.5f);
        mPath.moveTo(19.0f, 12.0f);
        mPath.rCubicTo(-2.8f, 0.0f, -5.0f, 2.2f, -5.0f, 5.0f);
        mPath.rCubicTo(0.0f, 2.8000002f, 2.2f, 5.0f, 5.0f, 5.0f);
        mPath.rCubicTo(2.7999992f, 0.0f, 5.0f, -2.2f, 5.0f, -5.0f);
        mPath.rCubicTo(0.0f, -2.7999992f, -2.2f, -5.0f, -5.0f, -5.0f);
        mPath.close();
        mPath.moveTo(19.0f, 12.0f);
        mPath.rMoveTo(0.0f, 8.5f);
        mPath.rCubicTo(-1.9f, 0.0f, -3.5f, -1.6f, -3.5f, -3.5f);
        mPath.rCubicTo(0.0f, -1.8999996f, 1.6f, -3.5f, 3.5f, -3.5f);
        mPath.rCubicTo(1.8999996f, 0.0f, 3.5f, 1.6f, 3.5f, 3.5f);
        mPath.rCubicTo(0.0f, 1.8999996f, -1.6f, 3.5f, -3.5f, 3.5f);
        mPath.close();
        mPath.moveTo(19.0f, 20.5f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        if (mFillPaint == null) {
            mFillPaint = new Paint();
            mFillPaint.setStyle(Paint.Style.FILL);
            mFillPaint.setAntiAlias(true);
        }
        mFillPaint.setColor(applyAlpha(-16777216, 1.0f));
        mFillPaint.setColorFilter(filter);
        canvas.drawPath(mRenderPath, mFillPaint);

    }

}