package com.github.megatronking.svg.iconlibs;

import android.content.Context;
import android.graphics.Canvas;
import android.graphics.ColorFilter;
import android.graphics.Paint;

import com.github.megatronking.svg.support.SVGRenderer;

/**
 * AUTO-GENERATED FILE.  DO NOT MODIFY.
 * 
 * This class was automatically generated by the
 * SVG-Generator. It should not be modified by hand.
 */
public class ic_local_laundry_service extends SVGRenderer {

    public ic_local_laundry_service(Context context) {
        super(context);
        mAlpha = 1.0f;
        mWidth = dip2px(24.0f);
        mHeight = dip2px(24.0f);
    }

    @Override
    public void render(Canvas canvas, int w, int h, ColorFilter filter) {
        final float scaleX = w / 24.0f;
        final float scaleY = h / 24.0f;
        
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(9.17f, 16.83f);
        mPath.rCubicTo(1.56f, 1.56f, 4.1f, 1.56f, 5.66f, 0.0f);
        mPath.rCubicTo(1.56f, -1.56f, 1.56f, -4.1f, 0.0f, -5.66f);
        mPath.rLineTo(-5.66f, 5.66f);
        mPath.close();
        mPath.moveTo(9.17f, 16.83f);
        mPath.moveTo(18.0f, 2.01f);
        mPath.lineTo(6.0f, 2.0f);
        mPath.rCubicTo(-1.11f, 0.0f, -2.0f, 0.89f, -2.0f, 2.0f);
        mPath.rLineTo(0f, 16.0f);
        mPath.rCubicTo(0.0f, 1.11f, 0.89f, 2.0f, 2.0f, 2.0f);
        mPath.rLineTo(12.0f, 0f);
        mPath.rCubicTo(1.11f, 0.0f, 2.0f, -0.89f, 2.0f, -2.0f);
        mPath.lineTo(20.0f, 4.0f);
        mPath.rCubicTo(0.0f, -1.11f, -0.89f, -1.99f, -2.0f, -1.99f);
        mPath.close();
        mPath.moveTo(18.0f, 2.01f);
        mPath.moveTo(10.0f, 4.0f);
        mPath.rCubicTo(0.55f, 0.0f, 1.0f, 0.45f, 1.0f, 1.0f);
        mPath.rCubicTo(0.0f, 0.5500002f, -0.45f, 1.0f, -1.0f, 1.0f);
        mPath.rCubicTo(-0.5500002f, 0.0f, -1.0f, -0.45f, -1.0f, -1.0f);
        mPath.rCubicTo(0.0f, -0.5500002f, 0.45f, -1.0f, 1.0f, -1.0f);
        mPath.close();
        mPath.moveTo(10.0f, 4.0f);
        mPath.moveTo(7.0f, 4.0f);
        mPath.rCubicTo(0.55f, 0.0f, 1.0f, 0.45f, 1.0f, 1.0f);
        mPath.rCubicTo(0.0f, 0.5500002f, -0.45f, 1.0f, -1.0f, 1.0f);
        mPath.rCubicTo(-0.5500002f, 0.0f, -1.0f, -0.45f, -1.0f, -1.0f);
        mPath.rCubicTo(0.0f, -0.5500002f, 0.45f, -1.0f, 1.0f, -1.0f);
        mPath.close();
        mPath.moveTo(7.0f, 4.0f);
        mPath.rMoveTo(5.0f, 16.0f);
        mPath.rCubicTo(-3.31f, 0.0f, -6.0f, -2.69f, -6.0f, -6.0f);
        mPath.rCubicTo(0.0f, -3.3099995f, 2.69f, -6.0f, 6.0f, -6.0f);
        mPath.rCubicTo(3.3099995f, 0.0f, 6.0f, 2.69f, 6.0f, 6.0f);
        mPath.rCubicTo(0.0f, 3.3099995f, -2.69f, 6.0f, -6.0f, 6.0f);
        mPath.close();
        mPath.moveTo(12.0f, 20.0f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        if (mFillPaint == null) {
            mFillPaint = new Paint();
            mFillPaint.setStyle(Paint.Style.FILL);
            mFillPaint.setAntiAlias(true);
        }
        mFillPaint.setColor(applyAlpha(-16777216, 1.0f));
        mFillPaint.setColorFilter(filter);
        canvas.drawPath(mRenderPath, mFillPaint);

    }

}