package com.github.megatronking.svg.iconlibs;

import android.content.Context;
import android.graphics.Canvas;
import android.graphics.ColorFilter;
import android.graphics.Paint;

import com.github.megatronking.svg.support.SVGRenderer;

/**
 * AUTO-GENERATED FILE.  DO NOT MODIFY.
 * 
 * This class was automatically generated by the
 * SVG-Generator. It should not be modified by hand.
 */
public class ic_local_library extends SVGRenderer {

    public ic_local_library(Context context) {
        super(context);
        mAlpha = 1.0f;
        mWidth = dip2px(24.0f);
        mHeight = dip2px(24.0f);
    }

    @Override
    public void render(Canvas canvas, int w, int h, ColorFilter filter) {
        final float scaleX = w / 24.0f;
        final float scaleY = h / 24.0f;
        
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(12.0f, 11.55f);
        mPath.cubicTo(9.64f, 9.35f, 6.48f, 8.0f, 3.0f, 8.0f);
        mPath.rLineTo(0f, 11.0f);
        mPath.rCubicTo(3.48f, 0.0f, 6.64f, 1.35f, 9.0f, 3.55f);
        mPath.rCubicTo(2.36f, -2.19f, 5.52f, -3.55f, 9.0f, -3.55f);
        mPath.lineTo(21.0f, 8.0f);
        mPath.rCubicTo(-3.48f, 0.0f, -6.64f, 1.35f, -9.0f, 3.55f);
        mPath.close();
        mPath.moveTo(12.0f, 11.55f);
        mPath.moveTo(12.0f, 8.0f);
        mPath.rCubicTo(1.66f, 0.0f, 3.0f, -1.34f, 3.0f, -3.0f);
        mPath.rCubicTo(0.0f, -1.6599998f, -1.34f, -3.0f, -3.0f, -3.0f);
        mPath.rCubicTo(-1.6599998f, 0.0f, -3.0f, 1.34f, -3.0f, 3.0f);
        mPath.rCubicTo(0.0f, 1.6599998f, 1.34f, 3.0f, 3.0f, 3.0f);
        mPath.close();
        mPath.moveTo(12.0f, 8.0f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        if (mFillPaint == null) {
            mFillPaint = new Paint();
            mFillPaint.setStyle(Paint.Style.FILL);
            mFillPaint.setAntiAlias(true);
        }
        mFillPaint.setColor(applyAlpha(-16777216, 1.0f));
        mFillPaint.setColorFilter(filter);
        canvas.drawPath(mRenderPath, mFillPaint);

    }

}