package com.github.megatronking.svg.iconlibs;

import android.content.Context;
import android.graphics.Canvas;
import android.graphics.ColorFilter;
import android.graphics.Paint;

import com.github.megatronking.svg.support.SVGRenderer;

/**
 * AUTO-GENERATED FILE.  DO NOT MODIFY.
 * 
 * This class was automatically generated by the
 * SVG-Generator. It should not be modified by hand.
 */
public class ic_map extends SVGRenderer {

    public ic_map(Context context) {
        super(context);
        mAlpha = 1.0f;
        mWidth = dip2px(24.0f);
        mHeight = dip2px(24.0f);
    }

    @Override
    public void render(Canvas canvas, int w, int h, ColorFilter filter) {
        final float scaleX = w / 24.0f;
        final float scaleY = h / 24.0f;
        
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(20.5f, 3.0f);
        mPath.rLineTo(-0.16f, 0.03f);
        mPath.lineTo(15.0f, 5.1f);
        mPath.lineTo(9.0f, 3.0f);
        mPath.lineTo(3.36f, 4.9f);
        mPath.rCubicTo(-0.21f, 0.07f, -0.36f, 0.25f, -0.36f, 0.48f);
        mPath.lineTo(3.0f, 20.5f);
        mPath.rCubicTo(0.0f, 0.28f, 0.22f, 0.5f, 0.5f, 0.5f);
        mPath.rLineTo(0.16f, -0.03f);
        mPath.lineTo(9.0f, 18.9f);
        mPath.rLineTo(6.0f, 2.1f);
        mPath.rLineTo(5.64f, -1.9f);
        mPath.rCubicTo(0.21f, -0.07f, 0.36f, -0.25f, 0.36f, -0.48f);
        mPath.lineTo(21.0f, 3.5f);
        mPath.rCubicTo(0.0f, -0.28f, -0.22f, -0.5f, -0.5f, -0.5f);
        mPath.close();
        mPath.moveTo(20.5f, 3.0f);
        mPath.moveTo(15.0f, 19.0f);
        mPath.rLineTo(-6.0f, -2.11f);
        mPath.lineTo(9.0f, 5.0f);
        mPath.rLineTo(6.0f, 2.11f);
        mPath.lineTo(15.0f, 19.0f);
        mPath.close();
        mPath.moveTo(15.0f, 19.0f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        if (mFillPaint == null) {
            mFillPaint = new Paint();
            mFillPaint.setStyle(Paint.Style.FILL);
            mFillPaint.setAntiAlias(true);
        }
        mFillPaint.setColor(applyAlpha(-16777216, 1.0f));
        mFillPaint.setColorFilter(filter);
        canvas.drawPath(mRenderPath, mFillPaint);

    }

}