package com.github.megatronking.svg.iconlibs;

import android.content.Context;
import android.graphics.Canvas;
import android.graphics.ColorFilter;
import android.graphics.Paint;

import com.github.megatronking.svg.support.SVGRenderer;

/**
 * AUTO-GENERATED FILE.  DO NOT MODIFY.
 * 
 * This class was automatically generated by the
 * SVG-Generator. It should not be modified by hand.
 */
public class ic_tram extends SVGRenderer {

    public ic_tram(Context context) {
        super(context);
        mAlpha = 1.0f;
        mWidth = dip2px(24.0f);
        mHeight = dip2px(24.0f);
    }

    @Override
    public void render(Canvas canvas, int w, int h, ColorFilter filter) {
        final float scaleX = w / 24.0f;
        final float scaleY = h / 24.0f;
        
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(19.0f, 16.94f);
        mPath.lineTo(19.0f, 8.5f);
        mPath.rCubicTo(0.0f, -2.79f, -2.61f, -3.4f, -6.01f, -3.49f);
        mPath.rLineTo(0.76f, -1.51f);
        mPath.lineTo(17.0f, 3.5000002f);
        mPath.lineTo(17.0f, 2.0f);
        mPath.lineTo(7.0f, 2.0f);
        mPath.rLineTo(0f, 1.5f);
        mPath.rLineTo(4.75f, 0f);
        mPath.rLineTo(-0.76f, 1.52f);
        mPath.cubicTo(7.86f, 5.11f, 5.0f, 5.73f, 5.0f, 8.5f);
        mPath.rLineTo(0f, 8.44f);
        mPath.rCubicTo(0.0f, 1.45f, 1.19f, 2.66f, 2.59f, 2.97f);
        mPath.lineTo(6.0f, 21.5f);
        mPath.rLineTo(0f, 0.5f);
        mPath.rLineTo(2.23f, 0f);
        mPath.rLineTo(2.0f, -2.0f);
        mPath.lineTo(14.0f, 20.0f);
        mPath.rLineTo(2.0f, 2.0f);
        mPath.rLineTo(2.0f, 0f);
        mPath.rLineTo(0f, -0.5f);
        mPath.lineTo(16.5f, 20.0f);
        mPath.rLineTo(-0.08f, 0f);
        mPath.rCubicTo(1.69f, 0.0f, 2.58f, -1.37f, 2.58f, -3.06f);
        mPath.close();
        mPath.moveTo(19.0f, 16.94f);
        mPath.rMoveTo(-7.0f, 1.56f);
        mPath.rCubicTo(-0.83f, 0.0f, -1.5f, -0.67f, -1.5f, -1.5f);
        mPath.rCubicTo(0.0f, -0.8299999f, 0.67f, -1.5f, 1.5f, -1.5f);
        mPath.rCubicTo(0.8299999f, 0.0f, 1.5f, 0.67f, 1.5f, 1.5f);
        mPath.rCubicTo(0.0f, 0.8299999f, -0.67f, 1.5f, -1.5f, 1.5f);
        mPath.close();
        mPath.moveTo(12.0f, 18.5f);
        mPath.rMoveTo(5.0f, -4.5f);
        mPath.lineTo(7.0f, 14.0f);
        mPath.lineTo(7.0f, 9.0f);
        mPath.rLineTo(10.0f, 0f);
        mPath.rLineTo(0f, 5.0f);
        mPath.close();
        mPath.moveTo(17.0f, 14.0f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        if (mFillPaint == null) {
            mFillPaint = new Paint();
            mFillPaint.setStyle(Paint.Style.FILL);
            mFillPaint.setAntiAlias(true);
        }
        mFillPaint.setColor(applyAlpha(-16777216, 1.0f));
        mFillPaint.setColorFilter(filter);
        canvas.drawPath(mRenderPath, mFillPaint);

    }

}