package com.github.megatronking.svg.iconlibs;

import android.content.Context;
import android.graphics.Canvas;
import android.graphics.ColorFilter;
import android.graphics.Paint;

import com.github.megatronking.svg.support.SVGRenderer;

/**
 * AUTO-GENERATED FILE.  DO NOT MODIFY.
 * 
 * This class was automatically generated by the
 * SVG-Generator. It should not be modified by hand.
 */
public class ic_nature extends SVGRenderer {

    public ic_nature(Context context) {
        super(context);
        mAlpha = 1.0f;
        mWidth = dip2px(24.0f);
        mHeight = dip2px(24.0f);
    }

    @Override
    public void render(Canvas canvas, int w, int h, ColorFilter filter) {
        final float scaleX = w / 24.0f;
        final float scaleY = h / 24.0f;
        
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(13.0f, 16.12f);
        mPath.rCubicTo(3.47f, -0.41f, 6.17f, -3.36f, 6.17f, -6.95f);
        mPath.rCubicTo(0.0f, -3.87f, -3.13f, -7.0f, -7.0f, -7.0f);
        mPath.rCubicTo(-3.8700008f, 0.0f, -7.0f, 3.13f, -7.0f, 7.0f);
        mPath.rCubicTo(0.0f, 3.47f, 2.52f, 6.34f, 5.83f, 6.89f);
        mPath.lineTo(11.0f, 20.0f);
        mPath.lineTo(5.0f, 20.0f);
        mPath.rLineTo(0f, 2.0f);
        mPath.rLineTo(14.0f, 0f);
        mPath.rLineTo(0f, -2.0f);
        mPath.rLineTo(-6.0f, 0f);
        mPath.rLineTo(0f, -3.88f);
        mPath.close();
        mPath.moveTo(13.0f, 16.12f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        if (mFillPaint == null) {
            mFillPaint = new Paint();
            mFillPaint.setStyle(Paint.Style.FILL);
            mFillPaint.setAntiAlias(true);
        }
        mFillPaint.setColor(applyAlpha(-16777216, 1.0f));
        mFillPaint.setColorFilter(filter);
        canvas.drawPath(mRenderPath, mFillPaint);

    }

}