package com.github.megatronking.svg.iconlibs;

import android.content.Context;
import android.graphics.Canvas;
import android.graphics.ColorFilter;
import android.graphics.Paint;

import com.github.megatronking.svg.support.SVGRenderer;

/**
 * AUTO-GENERATED FILE.  DO NOT MODIFY.
 * 
 * This class was automatically generated by the
 * SVG-Generator. It should not be modified by hand.
 */
public class ic_rotate_left extends SVGRenderer {

    public ic_rotate_left(Context context) {
        super(context);
        mAlpha = 1.0f;
        mWidth = dip2px(24.0f);
        mHeight = dip2px(24.0f);
    }

    @Override
    public void render(Canvas canvas, int w, int h, ColorFilter filter) {
        final float scaleX = w / 24.0f;
        final float scaleY = h / 24.0f;
        
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(7.11f, 8.53f);
        mPath.lineTo(5.7f, 7.11f);
        mPath.cubicTo(4.8f, 8.27f, 4.24f, 9.61f, 4.07f, 11.0f);
        mPath.rLineTo(2.02f, 0f);
        mPath.rCubicTo(0.14f, -0.87f, 0.49f, -1.72f, 1.02f, -2.47f);
        mPath.close();
        mPath.moveTo(7.11f, 8.53f);
        mPath.moveTo(6.09f, 13.0f);
        mPath.lineTo(4.07f, 13.0f);
        mPath.rCubicTo(0.17f, 1.39f, 0.72f, 2.73f, 1.62f, 3.89f);
        mPath.rLineTo(1.41f, -1.42f);
        mPath.rCubicTo(-0.52f, -0.75f, -0.87f, -1.59f, -1.01f, -2.47f);
        mPath.close();
        mPath.moveTo(6.09f, 13.0f);
        mPath.rMoveTo(1.01f, 5.32f);
        mPath.rCubicTo(1.16f, 0.9f, 2.51f, 1.44f, 3.9f, 1.61f);
        mPath.lineTo(11.0f, 17.9f);
        mPath.rCubicTo(-0.87f, -0.15f, -1.71f, -0.49f, -2.46f, -1.03f);
        mPath.lineTo(7.1f, 18.32f);
        mPath.close();
        mPath.moveTo(7.1000004f, 18.32f);
        mPath.moveTo(13.0f, 4.07f);
        mPath.lineTo(13.0f, 1.0f);
        mPath.lineTo(8.45f, 5.55f);
        mPath.lineTo(13.0f, 10.0f);
        mPath.lineTo(13.0f, 6.09f);
        mPath.rCubicTo(2.84f, 0.48f, 5.0f, 2.94f, 5.0f, 5.91f);
        mPath.rCubicTo(0.0f, 2.9699993f, -2.16f, 5.43f, -5.0f, 5.91f);
        mPath.rLineTo(0f, 2.02f);
        mPath.rCubicTo(3.95f, -0.49f, 7.0f, -3.85f, 7.0f, -7.93f);
        mPath.rCubicTo(0.0f, -4.08f, -3.05f, -7.44f, -7.0f, -7.93f);
        mPath.close();
        mPath.moveTo(13.0f, 4.07f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        if (mFillPaint == null) {
            mFillPaint = new Paint();
            mFillPaint.setStyle(Paint.Style.FILL);
            mFillPaint.setAntiAlias(true);
        }
        mFillPaint.setColor(applyAlpha(-16777216, 1.0f));
        mFillPaint.setColorFilter(filter);
        canvas.drawPath(mRenderPath, mFillPaint);

    }

}