package com.github.megatronking.svg.iconlibs;

import android.content.Context;
import android.graphics.Canvas;
import android.graphics.ColorFilter;
import android.graphics.Paint;

import com.github.megatronking.svg.support.SVGRenderer;

/**
 * AUTO-GENERATED FILE.  DO NOT MODIFY.
 * 
 * This class was automatically generated by the
 * SVG-Generator. It should not be modified by hand.
 */
public class ic_timer extends SVGRenderer {

    public ic_timer(Context context) {
        super(context);
        mAlpha = 1.0f;
        mWidth = dip2px(24.0f);
        mHeight = dip2px(24.0f);
    }

    @Override
    public void render(Canvas canvas, int w, int h, ColorFilter filter) {
        final float scaleX = w / 24.0f;
        final float scaleY = h / 24.0f;
        
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(15.0f, 1.0f);
        mPath.lineTo(9.0f, 1.0f);
        mPath.rLineTo(0f, 2.0f);
        mPath.rLineTo(6.0f, 0f);
        mPath.lineTo(15.0f, 1.0f);
        mPath.close();
        mPath.moveTo(15.0f, 1.0f);
        mPath.rMoveTo(-4.0f, 13.0f);
        mPath.rLineTo(2.0f, 0f);
        mPath.lineTo(13.0f, 8.0f);
        mPath.rLineTo(-2.0f, 0f);
        mPath.rLineTo(0f, 6.0f);
        mPath.close();
        mPath.moveTo(11.0f, 14.0f);
        mPath.rMoveTo(8.03f, -6.61f);
        mPath.rLineTo(1.42f, -1.42f);
        mPath.rCubicTo(-0.43f, -0.51f, -0.9f, -0.99f, -1.41f, -1.41f);
        mPath.rLineTo(-1.42f, 1.42f);
        mPath.cubicTo(16.07f, 4.74f, 14.12f, 4.0f, 12.0f, 4.0f);
        mPath.rCubicTo(-4.97f, 0.0f, -9.0f, 4.03f, -9.0f, 9.0f);
        mPath.rCubicTo(0.0f, 4.9699993f, 4.02f, 9.0f, 9.0f, 9.0f);
        mPath.rCubicTo(4.98f, 0.0f, 9.0f, -4.03f, 9.0f, -9.0f);
        mPath.rCubicTo(0.0f, -2.12f, -0.74f, -4.07f, -1.97f, -5.61f);
        mPath.close();
        mPath.moveTo(19.029999f, 7.39f);
        mPath.moveTo(12.0f, 20.0f);
        mPath.rCubicTo(-3.87f, 0.0f, -7.0f, -3.13f, -7.0f, -7.0f);
        mPath.rCubicTo(0.0f, -3.869999f, 3.13f, -7.0f, 7.0f, -7.0f);
        mPath.rCubicTo(3.87f, 0.0f, 7.0f, 3.13f, 7.0f, 7.0f);
        mPath.rCubicTo(0.0f, 3.87f, -3.13f, 7.0f, -7.0f, 7.0f);
        mPath.close();
        mPath.moveTo(12.0f, 20.0f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        if (mFillPaint == null) {
            mFillPaint = new Paint();
            mFillPaint.setStyle(Paint.Style.FILL);
            mFillPaint.setAntiAlias(true);
        }
        mFillPaint.setColor(applyAlpha(-16777216, 1.0f));
        mFillPaint.setColorFilter(filter);
        canvas.drawPath(mRenderPath, mFillPaint);

    }

}