package com.github.megatronking.svg.iconlibs;

import android.content.Context;
import android.graphics.Canvas;
import android.graphics.ColorFilter;
import android.graphics.Paint;

import com.github.megatronking.svg.support.SVGRenderer;

/**
 * AUTO-GENERATED FILE.  DO NOT MODIFY.
 * 
 * This class was automatically generated by the
 * SVG-Generator. It should not be modified by hand.
 */
public class ic_timer_10 extends SVGRenderer {

    public ic_timer_10(Context context) {
        super(context);
        mAlpha = 1.0f;
        mWidth = dip2px(24.0f);
        mHeight = dip2px(24.0f);
    }

    @Override
    public void render(Canvas canvas, int w, int h, ColorFilter filter) {
        final float scaleX = w / 24.0f;
        final float scaleY = h / 24.0f;
        
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(0.0f, 7.72f);
        mPath.lineTo(0.0f, 9.4f);
        mPath.rLineTo(3.0f, -1.0f);
        mPath.lineTo(3.0f, 18.0f);
        mPath.rLineTo(2.0f, 0f);
        mPath.lineTo(5.0f, 6.0f);
        mPath.rLineTo(-0.25f, 0f);
        mPath.lineTo(0.0f, 7.72f);
        mPath.close();
        mPath.moveTo(0.0f, 7.72f);
        mPath.rMoveTo(23.78f, 6.65f);
        mPath.rCubicTo(-0.14f, -0.28f, -0.35f, -0.53f, -0.63f, -0.74f);
        mPath.rCubicTo(-0.28f, -0.21f, -0.61f, -0.39f, -1.01f, -0.53f);
        mPath.rCubicTo(-0.39999962f, -0.13999939f, -0.85f, -0.27f, -1.35f, -0.38f);
        mPath.rCubicTo(-0.35f, -0.07f, -0.64f, -0.15f, -0.87f, -0.23f);
        mPath.rCubicTo(-0.23f, -0.08f, -0.41f, -0.16f, -0.55f, -0.25f);
        mPath.rCubicTo(-0.14f, -0.09f, -0.23f, -0.19f, -0.28f, -0.3f);
        mPath.rCubicTo(-0.05f, -0.11f, -0.08f, -0.24f, -0.08f, -0.39f);
        mPath.rCubicTo(0.0f, -0.14f, 0.03f, -0.28f, 0.09f, -0.41f);
        mPath.rCubicTo(0.06f, -0.13f, 0.15f, -0.25f, 0.27f, -0.34f);
        mPath.rCubicTo(0.12f, -0.1f, 0.27f, -0.18f, 0.45f, -0.24f);
        mPath.rCubicTo(0.1800003f, -0.059999466f, 0.4f, -0.09f, 0.64f, -0.09f);
        mPath.rCubicTo(0.25f, 0.0f, 0.47f, 0.04f, 0.66f, 0.11f);
        mPath.rCubicTo(0.19f, 0.07f, 0.35f, 0.17f, 0.48f, 0.29f);
        mPath.rCubicTo(0.13f, 0.12f, 0.22f, 0.26f, 0.29f, 0.42f);
        mPath.rCubicTo(0.06f, 0.16f, 0.1f, 0.32f, 0.1f, 0.49f);
        mPath.rLineTo(1.95f, 0f);
        mPath.rCubicTo(0.0f, -0.39f, -0.08f, -0.75f, -0.24f, -1.09f);
        mPath.rCubicTo(-0.16f, -0.34f, -0.39f, -0.63f, -0.69f, -0.88f);
        mPath.rCubicTo(-0.3f, -0.25f, -0.66f, -0.44f, -1.09f, -0.59f);
        mPath.cubicTo(21.49f, 9.07f, 21.0f, 9.0f, 20.46f, 9.0f);
        mPath.rCubicTo(-0.51f, 0.0f, -0.98f, 0.07f, -1.39f, 0.21f);
        mPath.rCubicTo(-0.41f, 0.14f, -0.77f, 0.33f, -1.06f, 0.57f);
        mPath.rCubicTo(-0.29f, 0.24f, -0.51f, 0.52f, -0.67f, 0.84f);
        mPath.rCubicTo(-0.16f, 0.32f, -0.23f, 0.65f, -0.23f, 1.01f);
        mPath.rCubicTo(0.0f, 0.3600006f, 0.08f, 0.69f, 0.23f, 0.96f);
        mPath.rCubicTo(0.15f, 0.28f, 0.36f, 0.52f, 0.64f, 0.73f);
        mPath.rCubicTo(0.27f, 0.21f, 0.6f, 0.38f, 0.98f, 0.53f);
        mPath.rCubicTo(0.38f, 0.14f, 0.81f, 0.26f, 1.27f, 0.36f);
        mPath.rCubicTo(0.39f, 0.08f, 0.71f, 0.17f, 0.95f, 0.26f);
        mPath.rCubicTo(0.24000168f, 0.09000015f, 0.43f, 0.19f, 0.57f, 0.29f);
        mPath.rCubicTo(0.13f, 0.1f, 0.22f, 0.22f, 0.27f, 0.34f);
        mPath.rCubicTo(0.05f, 0.12f, 0.07f, 0.25f, 0.07f, 0.39f);
        mPath.rCubicTo(0.0f, 0.32f, -0.13f, 0.57f, -0.4f, 0.77f);
        mPath.rCubicTo(-0.27f, 0.2f, -0.66f, 0.29f, -1.17f, 0.29f);
        mPath.rCubicTo(-0.22f, 0.0f, -0.43f, -0.02f, -0.64f, -0.08f);
        mPath.rCubicTo(-0.21f, -0.05f, -0.4f, -0.13f, -0.56f, -0.24f);
        mPath.rCubicTo(-0.17f, -0.11f, -0.3f, -0.26f, -0.41f, -0.44f);
        mPath.rCubicTo(-0.11f, -0.18f, -0.17f, -0.41f, -0.18f, -0.67f);
        mPath.rLineTo(-1.89f, 0f);
        mPath.rCubicTo(0.0f, 0.36f, 0.08f, 0.71f, 0.24f, 1.05f);
        mPath.rCubicTo(0.16f, 0.34f, 0.39f, 0.65f, 0.7f, 0.93f);
        mPath.rCubicTo(0.31f, 0.27f, 0.69f, 0.49f, 1.15f, 0.66f);
        mPath.rCubicTo(0.46f, 0.17f, 0.98f, 0.25f, 1.58f, 0.25f);
        mPath.rCubicTo(0.53f, 0.0f, 1.01f, -0.06f, 1.44f, -0.19f);
        mPath.rCubicTo(0.43f, -0.13f, 0.8f, -0.31f, 1.11f, -0.54f);
        mPath.rCubicTo(0.31f, -0.23f, 0.54f, -0.51f, 0.71f, -0.83f);
        mPath.rCubicTo(0.17f, -0.32f, 0.25f, -0.67f, 0.25f, -1.06f);
        mPath.rCubicTo(-0.02f, -0.4f, -0.09f, -0.74f, -0.24f, -1.02f);
        mPath.close();
        mPath.moveTo(23.78f, 14.37f);
        mPath.rMoveTo(-9.96f, -7.32f);
        mPath.rCubicTo(-0.34f, -0.4f, -0.75f, -0.7f, -1.23f, -0.88f);
        mPath.rCubicTo(-0.47f, -0.18f, -1.01f, -0.27f, -1.59f, -0.27f);
        mPath.rCubicTo(-0.58f, 0.0f, -1.11f, 0.09f, -1.59f, 0.27f);
        mPath.rCubicTo(-0.48f, 0.18f, -0.89f, 0.47f, -1.23f, 0.88f);
        mPath.rCubicTo(-0.34f, 0.41f, -0.6f, 0.93f, -0.79f, 1.59f);
        mPath.rCubicTo(-0.18f, 0.65f, -0.28f, 1.45f, -0.28f, 2.39f);
        mPath.rLineTo(0f, 1.92f);
        mPath.rCubicTo(0.0f, 0.94f, 0.09f, 1.74f, 0.28f, 2.39f);
        mPath.rCubicTo(0.19f, 0.66f, 0.45f, 1.19f, 0.8f, 1.6f);
        mPath.rCubicTo(0.34f, 0.41f, 0.75f, 0.71f, 1.23f, 0.89f);
        mPath.rCubicTo(0.48f, 0.18f, 1.01f, 0.28f, 1.59f, 0.28f);
        mPath.rCubicTo(0.59f, 0.0f, 1.12f, -0.09f, 1.59f, -0.28f);
        mPath.rCubicTo(0.48f, -0.18f, 0.88f, -0.48f, 1.22f, -0.89f);
        mPath.rCubicTo(0.34f, -0.41f, 0.6f, -0.94f, 0.78f, -1.6f);
        mPath.rCubicTo(0.18f, -0.65f, 0.28f, -1.45f, 0.28f, -2.39f);
        mPath.rLineTo(0f, -1.92f);
        mPath.rCubicTo(0.0f, -0.94f, -0.09f, -1.74f, -0.28f, -2.39f);
        mPath.rCubicTo(-0.18f, -0.66f, -0.44f, -1.19f, -0.78f, -1.59f);
        mPath.close();
        mPath.moveTo(13.820001f, 7.0499997f);
        mPath.rMoveTo(-0.92f, 6.17f);
        mPath.rCubicTo(0.0f, 0.6f, -0.04f, 1.11f, -0.12f, 1.53f);
        mPath.rCubicTo(-0.08f, 0.42f, -0.2f, 0.76f, -0.36f, 1.02f);
        mPath.rCubicTo(-0.16f, 0.26f, -0.36f, 0.45f, -0.59f, 0.57f);
        mPath.rCubicTo(-0.23f, 0.12f, -0.51f, 0.18f, -0.82f, 0.18f);
        mPath.rCubicTo(-0.3f, 0.0f, -0.58f, -0.06f, -0.82f, -0.18f);
        mPath.rCubicTo(-0.23999977f, -0.12000084f, -0.44f, -0.31f, -0.6f, -0.57f);
        mPath.rCubicTo(-0.16f, -0.26f, -0.29f, -0.6f, -0.38f, -1.02f);
        mPath.rCubicTo(-0.09f, -0.42f, -0.13f, -0.93f, -0.13f, -1.53f);
        mPath.rLineTo(0f, -2.5f);
        mPath.rCubicTo(0.0f, -0.6f, 0.04f, -1.11f, 0.13f, -1.52f);
        mPath.rCubicTo(0.09f, -0.41f, 0.21f, -0.74f, 0.38f, -1.0f);
        mPath.rCubicTo(0.16f, -0.25f, 0.36f, -0.43f, 0.6f, -0.55f);
        mPath.rCubicTo(0.24f, -0.11f, 0.51f, -0.17f, 0.81f, -0.17f);
        mPath.rCubicTo(0.31f, 0.0f, 0.58f, 0.06f, 0.81f, 0.17f);
        mPath.rCubicTo(0.24f, 0.11f, 0.44f, 0.29f, 0.6f, 0.55f);
        mPath.rCubicTo(0.16f, 0.25f, 0.29f, 0.58f, 0.37f, 0.99f);
        mPath.rCubicTo(0.08f, 0.41f, 0.13f, 0.92f, 0.13f, 1.52f);
        mPath.rLineTo(0f, 2.51f);
        mPath.close();
        mPath.moveTo(12.900001f, 13.219999f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        if (mFillPaint == null) {
            mFillPaint = new Paint();
            mFillPaint.setStyle(Paint.Style.FILL);
            mFillPaint.setAntiAlias(true);
        }
        mFillPaint.setColor(applyAlpha(-16777216, 1.0f));
        mFillPaint.setColorFilter(filter);
        canvas.drawPath(mRenderPath, mFillPaint);

    }

}