package com.github.megatronking.svg.iconlibs;

import android.content.Context;
import android.graphics.Canvas;
import android.graphics.ColorFilter;
import android.graphics.Paint;

import com.github.megatronking.svg.support.SVGRenderer;

/**
 * AUTO-GENERATED FILE.  DO NOT MODIFY.
 * 
 * This class was automatically generated by the
 * SVG-Generator. It should not be modified by hand.
 */
public class ic_wb_auto extends SVGRenderer {

    public ic_wb_auto(Context context) {
        super(context);
        mAlpha = 1.0f;
        mWidth = dip2px(24.0f);
        mHeight = dip2px(24.0f);
    }

    @Override
    public void render(Canvas canvas, int w, int h, ColorFilter filter) {
        final float scaleX = w / 24.0f;
        final float scaleY = h / 24.0f;
        
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(6.85f, 12.65f);
        mPath.rLineTo(2.3f, 0f);
        mPath.lineTo(8.0f, 9.0f);
        mPath.rLineTo(-1.15f, 3.65f);
        mPath.close();
        mPath.moveTo(6.85f, 12.65f);
        mPath.moveTo(22.0f, 7.0f);
        mPath.rLineTo(-1.2f, 6.29f);
        mPath.lineTo(19.3f, 7.0f);
        mPath.rLineTo(-1.6f, 0f);
        mPath.rLineTo(-1.49f, 6.29f);
        mPath.lineTo(15.0f, 7.0f);
        mPath.rLineTo(-0.76f, 0f);
        mPath.cubicTo(12.77f, 5.17f, 10.53f, 4.0f, 8.0f, 4.0f);
        mPath.rCubicTo(-4.42f, 0.0f, -8.0f, 3.58f, -8.0f, 8.0f);
        mPath.rCubicTo(0.0f, 4.42f, 3.58f, 8.0f, 8.0f, 8.0f);
        mPath.rCubicTo(3.13f, 0.0f, 5.84f, -1.81f, 7.15f, -4.43f);
        mPath.rLineTo(0.1f, 0.43f);
        mPath.lineTo(17.0f, 16.0f);
        mPath.rLineTo(1.5f, -6.1f);
        mPath.lineTo(20.0f, 16.0f);
        mPath.rLineTo(1.75f, 0f);
        mPath.rLineTo(2.05f, -9.0f);
        mPath.lineTo(22.0f, 7.0f);
        mPath.close();
        mPath.moveTo(22.0f, 7.0f);
        mPath.rMoveTo(-11.7f, 9.0f);
        mPath.rLineTo(-0.7f, -2.0f);
        mPath.lineTo(6.4f, 14.0f);
        mPath.rLineTo(-0.7f, 2.0f);
        mPath.lineTo(3.8f, 16.0f);
        mPath.lineTo(7.0f, 7.0f);
        mPath.rLineTo(2.0f, 0f);
        mPath.rLineTo(3.2f, 9.0f);
        mPath.rLineTo(-1.9f, 0f);
        mPath.close();
        mPath.moveTo(10.3f, 16.0f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        if (mFillPaint == null) {
            mFillPaint = new Paint();
            mFillPaint.setStyle(Paint.Style.FILL);
            mFillPaint.setAntiAlias(true);
        }
        mFillPaint.setColor(applyAlpha(-16777216, 1.0f));
        mFillPaint.setColorFilter(filter);
        canvas.drawPath(mRenderPath, mFillPaint);

    }

}