package com.github.megatronking.svg.iconlibs;

import android.content.Context;
import android.graphics.Canvas;
import android.graphics.ColorFilter;
import android.graphics.Paint;

import com.github.megatronking.svg.support.SVGRenderer;

/**
 * AUTO-GENERATED FILE.  DO NOT MODIFY.
 * 
 * This class was automatically generated by the
 * SVG-Generator. It should not be modified by hand.
 */
public class ic_fiber_dvr extends SVGRenderer {

    public ic_fiber_dvr(Context context) {
        super(context);
        mAlpha = 1.0f;
        mWidth = dip2px(24.0f);
        mHeight = dip2px(24.0f);
    }

    @Override
    public void render(Canvas canvas, int w, int h, ColorFilter filter) {
        final float scaleX = w / 24.0f;
        final float scaleY = h / 24.0f;
        
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(17.5f, 10.5f);
        mPath.rLineTo(2.0f, 0f);
        mPath.rLineTo(0f, 1.0f);
        mPath.rLineTo(-2.0f, 0f);
        mPath.close();
        mPath.moveTo(17.5f, 10.5f);
        mPath.rMoveTo(-13.0f, 0.0f);
        mPath.rLineTo(2.0f, 0f);
        mPath.rLineTo(0f, 3.0f);
        mPath.rLineTo(-2.0f, 0f);
        mPath.close();
        mPath.moveTo(4.5f, 10.5f);
        mPath.moveTo(21.0f, 3.0f);
        mPath.lineTo(3.0f, 3.0f);
        mPath.rCubicTo(-1.11f, 0.0f, -2.0f, 0.89f, -2.0f, 2.0f);
        mPath.rLineTo(0f, 14.0f);
        mPath.rCubicTo(0.0f, 1.1f, 0.89f, 2.0f, 2.0f, 2.0f);
        mPath.rLineTo(18.0f, 0f);
        mPath.rCubicTo(1.11f, 0.0f, 2.0f, -0.9f, 2.0f, -2.0f);
        mPath.lineTo(23.0f, 5.0f);
        mPath.rCubicTo(0.0f, -1.11f, -0.89f, -2.0f, -2.0f, -2.0f);
        mPath.close();
        mPath.moveTo(21.0f, 3.0f);
        mPath.moveTo(8.0f, 13.5f);
        mPath.rCubicTo(0.0f, 0.85f, -0.65f, 1.5f, -1.5f, 1.5f);
        mPath.lineTo(3.0f, 15.0f);
        mPath.lineTo(3.0f, 9.0f);
        mPath.rLineTo(3.5f, 0f);
        mPath.rCubicTo(0.85f, 0.0f, 1.5f, 0.65f, 1.5f, 1.5f);
        mPath.rLineTo(0f, 3.0f);
        mPath.close();
        mPath.moveTo(8.0f, 13.5f);
        mPath.rMoveTo(4.62f, 1.5f);
        mPath.rLineTo(-1.5f, 0f);
        mPath.lineTo(9.37f, 9.0f);
        mPath.rLineTo(1.5f, 0f);
        mPath.rLineTo(1.0f, 3.43f);
        mPath.rLineTo(1.0f, -3.43f);
        mPath.rLineTo(1.5f, 0f);
        mPath.rLineTo(-1.75f, 6.0f);
        mPath.close();
        mPath.moveTo(12.62f, 15.0f);
        mPath.moveTo(21.0f, 11.5f);
        mPath.rCubicTo(0.0f, 0.6f, -0.4f, 1.15f, -0.9f, 1.4f);
        mPath.lineTo(21.0f, 15.0f);
        mPath.rLineTo(-1.5f, 0f);
        mPath.rLineTo(-0.85f, -2.0f);
        mPath.lineTo(17.5f, 13.0f);
        mPath.rLineTo(0f, 2.0f);
        mPath.lineTo(16.0f, 15.0f);
        mPath.lineTo(16.0f, 9.0f);
        mPath.rLineTo(3.5f, 0f);
        mPath.rCubicTo(0.85f, 0.0f, 1.5f, 0.65f, 1.5f, 1.5f);
        mPath.rLineTo(0f, 1.0f);
        mPath.close();
        mPath.moveTo(21.0f, 11.5f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        if (mFillPaint == null) {
            mFillPaint = new Paint();
            mFillPaint.setStyle(Paint.Style.FILL);
            mFillPaint.setAntiAlias(true);
        }
        mFillPaint.setColor(applyAlpha(-16777216, 1.0f));
        mFillPaint.setColorFilter(filter);
        canvas.drawPath(mRenderPath, mFillPaint);

    }

}