package com.github.megatronking.svg.iconlibs;

import android.content.Context;
import android.graphics.Canvas;
import android.graphics.ColorFilter;
import android.graphics.Paint;

import com.github.megatronking.svg.support.SVGRenderer;

/**
 * AUTO-GENERATED FILE.  DO NOT MODIFY.
 * 
 * This class was automatically generated by the
 * SVG-Generator. It should not be modified by hand.
 */
public class ic_mic_off extends SVGRenderer {

    public ic_mic_off(Context context) {
        super(context);
        mAlpha = 1.0f;
        mWidth = dip2px(24.0f);
        mHeight = dip2px(24.0f);
    }

    @Override
    public void render(Canvas canvas, int w, int h, ColorFilter filter) {
        final float scaleX = w / 24.0f;
        final float scaleY = h / 24.0f;
        
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(19.0f, 11.0f);
        mPath.rLineTo(-1.7f, 0f);
        mPath.rCubicTo(0.0f, 0.74f, -0.16f, 1.43f, -0.43f, 2.05f);
        mPath.rLineTo(1.23f, 1.23f);
        mPath.rCubicTo(0.56f, -0.98f, 0.9f, -2.09f, 0.9f, -3.28f);
        mPath.close();
        mPath.moveTo(19.0f, 11.0f);
        mPath.rMoveTo(-4.02f, 0.17f);
        mPath.rCubicTo(0.0f, -0.06f, 0.02f, -0.11f, 0.02f, -0.17f);
        mPath.lineTo(15.0f, 5.0f);
        mPath.rCubicTo(0.0f, -1.66f, -1.34f, -3.0f, -3.0f, -3.0f);
        mPath.cubicTo(10.34f, 2.0f, 9.0f, 3.34f, 9.0f, 5.0f);
        mPath.rLineTo(0f, 0.18f);
        mPath.rLineTo(5.98f, 5.99f);
        mPath.close();
        mPath.moveTo(14.98f, 11.17f);
        mPath.moveTo(4.27f, 3.0f);
        mPath.lineTo(3.0f, 4.27f);
        mPath.rLineTo(6.01f, 6.01f);
        mPath.lineTo(9.01f, 11.0f);
        mPath.rCubicTo(0.0f, 1.66f, 1.33f, 3.0f, 2.99f, 3.0f);
        mPath.rCubicTo(0.22f, 0.0f, 0.44f, -0.03f, 0.65f, -0.08f);
        mPath.rLineTo(1.66f, 1.66f);
        mPath.rCubicTo(-0.71f, 0.33f, -1.5f, 0.52f, -2.31f, 0.52f);
        mPath.rCubicTo(-2.76f, 0.0f, -5.3f, -2.1f, -5.3f, -5.1f);
        mPath.lineTo(5.0f, 11.0f);
        mPath.rCubicTo(0.0f, 3.41f, 2.72f, 6.23f, 6.0f, 6.72f);
        mPath.lineTo(11.0f, 21.0f);
        mPath.rLineTo(2.0f, 0f);
        mPath.rLineTo(0f, -3.28f);
        mPath.rCubicTo(0.91f, -0.13f, 1.77f, -0.45f, 2.54f, -0.9f);
        mPath.lineTo(19.73f, 21.0f);
        mPath.lineTo(21.0f, 19.73f);
        mPath.lineTo(4.27f, 3.0f);
        mPath.close();
        mPath.moveTo(4.27f, 3.0f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        if (mFillPaint == null) {
            mFillPaint = new Paint();
            mFillPaint.setStyle(Paint.Style.FILL);
            mFillPaint.setAntiAlias(true);
        }
        mFillPaint.setColor(applyAlpha(-16777216, 1.0f));
        mFillPaint.setColorFilter(filter);
        canvas.drawPath(mRenderPath, mFillPaint);

    }

}