package com.github.megatronking.svg.iconlibs;

import android.content.Context;
import android.graphics.Canvas;
import android.graphics.ColorFilter;
import android.graphics.Paint;

import com.github.megatronking.svg.support.SVGRenderer;

/**
 * AUTO-GENERATED FILE.  DO NOT MODIFY.
 * 
 * This class was automatically generated by the
 * SVG-Generator. It should not be modified by hand.
 */
public class ic_surround_sound extends SVGRenderer {

    public ic_surround_sound(Context context) {
        super(context);
        mAlpha = 1.0f;
        mWidth = dip2px(24.0f);
        mHeight = dip2px(24.0f);
    }

    @Override
    public void render(Canvas canvas, int w, int h, ColorFilter filter) {
        final float scaleX = w / 24.0f;
        final float scaleY = h / 24.0f;
        
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(20.0f, 4.0f);
        mPath.lineTo(4.0f, 4.0f);
        mPath.rCubicTo(-1.1f, 0.0f, -2.0f, 0.9f, -2.0f, 2.0f);
        mPath.rLineTo(0f, 12.0f);
        mPath.rCubicTo(0.0f, 1.1f, 0.9f, 2.0f, 2.0f, 2.0f);
        mPath.rLineTo(16.0f, 0f);
        mPath.rCubicTo(1.1f, 0.0f, 2.0f, -0.9f, 2.0f, -2.0f);
        mPath.lineTo(22.0f, 6.0f);
        mPath.rCubicTo(0.0f, -1.1f, -0.9f, -2.0f, -2.0f, -2.0f);
        mPath.close();
        mPath.moveTo(20.0f, 4.0f);
        mPath.moveTo(7.76f, 16.24f);
        mPath.rLineTo(-1.41f, 1.41f);
        mPath.cubicTo(4.78f, 16.1f, 4.0f, 14.05f, 4.0f, 12.0f);
        mPath.rCubicTo(0.0f, -2.05f, 0.78f, -4.1f, 2.34f, -5.66f);
        mPath.rLineTo(1.41f, 1.41f);
        mPath.cubicTo(6.59f, 8.93f, 6.0f, 10.46f, 6.0f, 12.0f);
        mPath.rCubicTo(0.0f, 1.54f, 0.59f, 3.07f, 1.76f, 4.24f);
        mPath.close();
        mPath.moveTo(7.76f, 16.24f);
        mPath.moveTo(12.0f, 16.0f);
        mPath.rCubicTo(-2.21f, 0.0f, -4.0f, -1.79f, -4.0f, -4.0f);
        mPath.rCubicTo(0.0f, -2.21f, 1.79f, -4.0f, 4.0f, -4.0f);
        mPath.rCubicTo(2.21f, 0.0f, 4.0f, 1.79f, 4.0f, 4.0f);
        mPath.rCubicTo(0.0f, 2.21f, -1.79f, 4.0f, -4.0f, 4.0f);
        mPath.close();
        mPath.moveTo(12.0f, 16.0f);
        mPath.rMoveTo(5.66f, 1.66f);
        mPath.rLineTo(-1.41f, -1.41f);
        mPath.cubicTo(17.41f, 15.07f, 18.0f, 13.54f, 18.0f, 12.0f);
        mPath.rCubicTo(0.0f, -1.54f, -0.59f, -3.07f, -1.76f, -4.24f);
        mPath.rLineTo(1.41f, -1.41f);
        mPath.cubicTo(19.22f, 7.9f, 20.0f, 9.95f, 20.0f, 12.0f);
        mPath.rCubicTo(0.0f, 2.05f, -0.78f, 4.1f, -2.34f, 5.66f);
        mPath.close();
        mPath.moveTo(17.66f, 17.66f);
        mPath.moveTo(12.0f, 10.0f);
        mPath.rCubicTo(-1.1f, 0.0f, -2.0f, 0.9f, -2.0f, 2.0f);
        mPath.rCubicTo(0.0f, 1.1000004f, 0.9f, 2.0f, 2.0f, 2.0f);
        mPath.rCubicTo(1.1000004f, 0.0f, 2.0f, -0.9f, 2.0f, -2.0f);
        mPath.rCubicTo(0.0f, -1.1000004f, -0.9f, -2.0f, -2.0f, -2.0f);
        mPath.close();
        mPath.moveTo(12.0f, 10.0f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        if (mFillPaint == null) {
            mFillPaint = new Paint();
            mFillPaint.setStyle(Paint.Style.FILL);
            mFillPaint.setAntiAlias(true);
        }
        mFillPaint.setColor(applyAlpha(-16777216, 1.0f));
        mFillPaint.setColorFilter(filter);
        canvas.drawPath(mRenderPath, mFillPaint);

    }

}