package com.github.megatronking.svg.iconlibs;

import android.content.Context;
import android.graphics.Canvas;
import android.graphics.ColorFilter;
import android.graphics.Paint;

import com.github.megatronking.svg.support.SVGRenderer;

/**
 * AUTO-GENERATED FILE.  DO NOT MODIFY.
 * 
 * This class was automatically generated by the
 * SVG-Generator. It should not be modified by hand.
 */
public class ic_sort_by_alpha extends SVGRenderer {

    public ic_sort_by_alpha(Context context) {
        super(context);
        mAlpha = 1.0f;
        mWidth = dip2px(24.0f);
        mHeight = dip2px(24.0f);
    }

    @Override
    public void render(Canvas canvas, int w, int h, ColorFilter filter) {
        final float scaleX = w / 24.0f;
        final float scaleY = h / 24.0f;
        
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(14.94f, 4.66f);
        mPath.rLineTo(-4.72f, 0f);
        mPath.rLineTo(2.36f, -2.36f);
        mPath.close();
        mPath.moveTo(14.94f, 4.66f);
        mPath.rMoveTo(-4.69f, 14.71f);
        mPath.rLineTo(4.66f, 0f);
        mPath.rLineTo(-2.33f, 2.33f);
        mPath.close();
        mPath.moveTo(10.25f, 19.369999f);
        mPath.moveTo(6.1f, 6.27f);
        mPath.lineTo(1.6f, 17.73f);
        mPath.rLineTo(1.84f, 0f);
        mPath.rLineTo(0.92f, -2.45f);
        mPath.rLineTo(5.11f, 0f);
        mPath.rLineTo(0.92f, 2.45f);
        mPath.rLineTo(1.84f, 0f);
        mPath.lineTo(7.74f, 6.27f);
        mPath.lineTo(6.1f, 6.27f);
        mPath.close();
        mPath.moveTo(6.1f, 6.27f);
        mPath.rMoveTo(-1.13f, 7.37f);
        mPath.rLineTo(1.94f, -5.18f);
        mPath.rLineTo(1.94f, 5.18f);
        mPath.lineTo(4.97f, 13.639999f);
        mPath.close();
        mPath.moveTo(4.97f, 13.639999f);
        mPath.rMoveTo(10.76f, 2.5f);
        mPath.rLineTo(6.12f, 0f);
        mPath.rLineTo(0f, 1.59f);
        mPath.rLineTo(-8.53f, 0f);
        mPath.rLineTo(0f, -1.29f);
        mPath.rLineTo(5.92f, -8.56f);
        mPath.rLineTo(-5.88f, 0f);
        mPath.rLineTo(0f, -1.6f);
        mPath.rLineTo(8.3f, 0f);
        mPath.rLineTo(0f, 1.26f);
        mPath.rLineTo(-5.93f, 8.6f);
        mPath.close();
        mPath.moveTo(15.73f, 16.14f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        if (mFillPaint == null) {
            mFillPaint = new Paint();
            mFillPaint.setStyle(Paint.Style.FILL);
            mFillPaint.setAntiAlias(true);
        }
        mFillPaint.setColor(applyAlpha(-16777216, 1.0f));
        mFillPaint.setColorFilter(filter);
        canvas.drawPath(mRenderPath, mFillPaint);

    }

}