package com.github.megatronking.svg.iconlibs;

import android.content.Context;
import android.graphics.Canvas;
import android.graphics.ColorFilter;
import android.graphics.Paint;

import com.github.megatronking.svg.support.SVGRenderer;

/**
 * AUTO-GENERATED FILE.  DO NOT MODIFY.
 * 
 * This class was automatically generated by the
 * SVG-Generator. It should not be modified by hand.
 */
public class ic_slow_motion_video extends SVGRenderer {

    public ic_slow_motion_video(Context context) {
        super(context);
        mAlpha = 1.0f;
        mWidth = dip2px(24.0f);
        mHeight = dip2px(24.0f);
    }

    @Override
    public void render(Canvas canvas, int w, int h, ColorFilter filter) {
        final float scaleX = w / 24.0f;
        final float scaleY = h / 24.0f;
        
        mPath.reset();
        mRenderPath.reset();
        
        mFinalPathMatrix.setValues(new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 0.0f, 0.0f, 0.0f, 1.0f});
        mFinalPathMatrix.postScale(scaleX, scaleY);
        
        mPath.moveTo(13.05f, 9.79f);
        mPath.lineTo(10.0f, 7.5f);
        mPath.rLineTo(0f, 9.0f);
        mPath.rLineTo(3.05f, -2.29f);
        mPath.lineTo(16.0f, 12.0f);
        mPath.close();
        mPath.moveTo(13.05f, 9.79f);
        mPath.rMoveTo(0.0f, 0.0f);
        mPath.lineTo(10.0f, 7.5f);
        mPath.rLineTo(0f, 9.0f);
        mPath.rLineTo(3.05f, -2.29f);
        mPath.lineTo(16.0f, 12.0f);
        mPath.close();
        mPath.moveTo(13.05f, 9.79f);
        mPath.rMoveTo(0.0f, 0.0f);
        mPath.lineTo(10.0f, 7.5f);
        mPath.rLineTo(0f, 9.0f);
        mPath.rLineTo(3.05f, -2.29f);
        mPath.lineTo(16.0f, 12.0f);
        mPath.close();
        mPath.moveTo(13.05f, 9.79f);
        mPath.moveTo(11.0f, 4.07f);
        mPath.lineTo(11.0f, 2.05f);
        mPath.rCubicTo(-2.01f, 0.2f, -3.84f, 1.0f, -5.32f, 2.21f);
        mPath.lineTo(7.1f, 5.69f);
        mPath.rCubicTo(1.11f, -0.86f, 2.44f, -1.44f, 3.9f, -1.62f);
        mPath.close();
        mPath.moveTo(11.0f, 4.07f);
        mPath.moveTo(5.69f, 7.1f);
        mPath.lineTo(4.26f, 5.68f);
        mPath.cubicTo(3.05f, 7.16f, 2.25f, 8.99f, 2.05f, 11.0f);
        mPath.rLineTo(2.02f, 0f);
        mPath.rCubicTo(0.18f, -1.46f, 0.76f, -2.79f, 1.62f, -3.9f);
        mPath.close();
        mPath.moveTo(5.69f, 7.1f);
        mPath.moveTo(4.07f, 13.0f);
        mPath.lineTo(2.05f, 13.0f);
        mPath.rCubicTo(0.2f, 2.01f, 1.0f, 3.84f, 2.21f, 5.32f);
        mPath.rLineTo(1.43f, -1.43f);
        mPath.rCubicTo(-0.86f, -1.1f, -1.44f, -2.43f, -1.62f, -3.89f);
        mPath.close();
        mPath.moveTo(4.07f, 13.0f);
        mPath.rMoveTo(1.61f, 6.74f);
        mPath.cubicTo(7.16f, 20.95f, 9.0f, 21.75f, 11.0f, 21.95f);
        mPath.rLineTo(0f, -2.02f);
        mPath.rCubicTo(-1.46f, -0.18f, -2.79f, -0.76f, -3.9f, -1.62f);
        mPath.rLineTo(-1.42f, 1.43f);
        mPath.close();
        mPath.moveTo(5.6800003f, 19.74f);
        mPath.moveTo(22.0f, 12.0f);
        mPath.rCubicTo(0.0f, 5.16f, -3.92f, 9.42f, -8.95f, 9.95f);
        mPath.rLineTo(0f, -2.02f);
        mPath.cubicTo(16.97f, 19.41f, 20.0f, 16.05f, 20.0f, 12.0f);
        mPath.rCubicTo(0.0f, -4.049999f, -3.03f, -7.41f, -6.95f, -7.93f);
        mPath.lineTo(13.05f, 2.05f);
        mPath.cubicTo(18.08f, 2.58f, 22.0f, 6.84f, 22.0f, 12.0f);
        mPath.close();
        mPath.moveTo(22.0f, 12.0f);
        
        mRenderPath.addPath(mPath, mFinalPathMatrix);
        if (mFillPaint == null) {
            mFillPaint = new Paint();
            mFillPaint.setStyle(Paint.Style.FILL);
            mFillPaint.setAntiAlias(true);
        }
        mFillPaint.setColor(applyAlpha(-16777216, 1.0f));
        mFillPaint.setColorFilter(filter);
        canvas.drawPath(mRenderPath, mFillPaint);

    }

}